### ISSUE TITLE
How to externd pyblast to support half float?

### ISSUE THREAD

**Issue by TaihuLight** [CNugteren/CLBlast#334] opened 2018-11-19 01:16 UTC
To call the routines like Haxy, and HGEMM, How to modify pyclblast.pyx and to enable pyclblast to support half-precision?
@kodonnell @CNugteren @kpot 
I try to add the following code to enable pyclblast to support half-precision GEMM, but it get wrong results without warings or error tips?
```
cdef extern from "clblast_half.h":
    ctypedef unsigned short cl_half

    if dtype == np.dtype("float16"):
        err = CLBlastHgemm(CLBlastLayoutRowMajor, a_transpose, b_transpose, m, n, k, <cl_half>alpha, a_buffer, a_offset, a_ld, b_buffer, b_offset, b_ld, <cl_half>beta, c_buffer, c_offset, c_ld, &command_queue, &event)
```
The code is 
[sgemm16.py.tar.gz](https://github.com/CNugteren/CLBlast/files/2591573/sgemm16.py.tar.gz)
and the output is 
```
python sgemm16.py 
# Setting up OpenCL
Choose platform:
[0] <pyopencl.Platform 'Intel(R) OpenCL' at 0x2dfdfd0>
[1] <pyopencl.Platform 'NVIDIA CUDA' at 0x2ee9380>
Choice [0]:0
Choose device(s):
[0] <pyopencl.Device 'Intel(R) HD Graphics' on 'Intel(R) OpenCL' at 0x2e84b30>
[1] <pyopencl.Device 'Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz' on 'Intel(R) OpenCL' at 0x2e7bd58>
Choice, comma-separated [0]:0
Set the environment variable PYOPENCL_CTX='0:0' to avoid being asked again.
# Setting up Numpy arrays
# Setting up OpenCL arrays
# Example level-3 operation: GEMM
# Matrix C result: [[  5.96046448e-08   1.19209290e-07   1.19209290e-07]
 [  5.96046448e-08   5.96046448e-08   0.00000000e+00]]
<pyopencl._cl.Event object at 0x7f2138cf28a0>
# Expected result: [[ 1.42480469  1.56640625  1.54785156]
 [ 0.75927734  0.85253906  0.45214844]]
```
How to modify pyclblast.pyx in order to pyclblast support half-precision GEMM?

**Comment by kodonnell** [comment] 2018-11-19 06:49
I don't think I can easily test, but you do have

```
x = clc.get().astype(np.float32)
```

Not sure if that'd affect things. If you're looking for performance, I vaguely recall trying fp16 myself, but it was a lot slower than fp32 overall - numpy's fp16 support was the bottleneck, if I remember correctly.

Also - do the fp16 gemm tests all pass?

**Comment by TaihuLight** [comment] 2018-11-19 09:06
@kodonnell 
(1) numpy's fp16 is lower than its fp32, I only calculate the time taken by kernels implemented with fp32 and fp16 on intel GPU, and ignore times convert between them.
(1) fp16 gemm with C is passed for clblast.

**Comment by kodonnell** [comment] 2018-11-19 10:17
Did you try fixing the suggestion above? I also don't know if numpy's fp16 is the same as CLBlast's.  You could always try debugging with 'trival' examples (e.g. multiplying by identity) to try and isolate the cause. I'm afraid I can't really much other than those vague suggestions.

**Comment by CNugteren** [comment] 2018-11-19 20:05
You have to make sure the FP16 conversion in Python is compatible with that with what CLBlast expects, as done e.g. [here in C](https://github.com/CNugteren/CLBlast/blob/master/include/clblast_half.h). Mimicking that function in Python code help perhaps?

**Comment by CNugteren** [comment] 2019-01-20 19:17
Is this still an issue? Have you had a look at @kodonnell's suggestions or mine? Would be good to know the outcome if you solved it!

**Comment by CNugteren** [comment] 2019-01-21 17:08
OK, but did you try our suggestions?

**Comment by CNugteren** [comment] 2019-01-22 20:17
I worked a little bit on 'properly' adding FP16 support to PyCLBlast. However, I can't make it work either with a small example. My changes are in the [CLBlast-334-pyclblast-half-precision-support](https://github.com/CNugteren/CLBlast/compare/CLBlast-334-pyclblast-half-precision-support?expand=1) branch.

There is a small AXPY example included, in which it is supposed to compute `alpha * x + y`, but CLBlast only return `y`. I suspect it has something to do with the `alpha` value not being passed properly through, causing it to be (close to) zero. I'll investigate some more when I have time.

**Comment by CNugteren** [comment] 2019-01-23 19:11
I've managed to make it work, thanks to a [fp32 to fp16 conversion function](https://github.com/CNugteren/CLBlast/blob/CLBlast-334-pyclblast-half-precision-support/src/pyclblast/src/pyclblast.pyx#L297) for Python I found online. By converting the alpha using this function and using NumPy's float16 data-type, everything seems to work.

I'll merge the branch in and release a new version on PyPi.

**Comment by CNugteren** [comment] 2019-01-25 16:41
I don't think that is needed, the result is just a NumPy array and NumPy can already do the cast for you.

**Comment by TaihuLight** [comment] 2019-01-26 05:06
It is an expected new that you release a new version of pyclblast 1.5.0 on PyPi.

**Comment by CNugteren** [comment] 2019-01-26 10:05
Not sure what you mean exactly, but keep in mind that PyCLBlast is independent of the CLBlast code itself, since it requires the actual CLBlast as a dependency. Thus, you shouldn't compare the release numbers there.

Anyway, I am closing this issue now, since I have just merged the changes into master, and have also released an updated PyCLBlast a few days ago on PyPi (version 1.2.0). You can update your installation with e.g. `pip install pyclblast -U`

**Closed by CNugteren** 2019-01-26 10:05 UTC
Labels: question
