### ISSUE TITLE
Compatibility with OpenCL 1.1 Embedded Profile on Vivante

### ISSUE THREAD

**Issue by simobrazz** [CNugteren/CLBlast#227] opened 2017-12-13 12:53 UTC
Hi guys,

I'm interested in using CLBlast with an embedded GPU (Vivante GC2000). The GPU only supports OpenCL 1.1 Embedded Profile. 

Does CLBlast support this OpenCL version?

I would appreciate any suggestions.

Thanks

**Comment by CNugteren** [comment] 2017-12-13 16:34
I didn't study this, but a quick look [here](https://stackoverflow.com/a/18528112/4807429) suggests that it should be possible. CLBlast is OpenCL 1.1 compatible and doesn't use advanced things like images and such. You could give it a try?

**Comment by simobrazz** [comment] 2017-12-13 17:01
With -DTESTS=ON against CBLAS (CPU ARM) it correctly compiles, but when I try to "make alltests" these errors appear:

$ make alltests
...
[100%] Built target clblast_test_xsyr
terminate called after throwing an instance of 'clblast::CLCudaAPIError'
  what():  OpenCL error: clGetPlatformIDs: -1001
CMakeFiles/alltests.dir/build.make:57: recipe for target 'CMakeFiles/alltests' failed
make[3]: *** [CMakeFiles/alltests] Aborted
CMakeFiles/Makefile2:1928: recipe for target 'CMakeFiles/alltests.dir/all' failed
make[2]: *** [CMakeFiles/alltests.dir/all] Error 2
CMakeFiles/Makefile2:1935: recipe for target 'CMakeFiles/alltests.dir/rule' failed
make[1]: *** [CMakeFiles/alltests.dir/rule] Error 2
Makefile:797: recipe for target 'alltests' failed
make: *** [alltests] Error 2

Why CLBlast call CLCudaAPIError?

**Comment by CNugteren** [comment] 2017-12-14 20:14
`make alltests` just runs all test binaries. Easier testing now with more info would be to just run an individual binary, say `./clblast_test_xaxpy`. You will then also see options to select a platform/device to test on.

Your error is from `clGetPlatformIDs` which is a regular OpenCL function, which returns -1001, which is not a CLBlast issue. Apparently there is something wrong with your OpenCL set-up on your platform. Try to search for `clGetPlatformIDs -1001` and you'll get e.g. [this](https://stackoverflow.com/questions/20335579/error-clgetplatformids-1001-when-running-opencl-code-linux?lq=1).

**Comment by CNugteren** [comment] 2017-12-23 12:59
@simobrazz Any update? I'm curious to know how good/bad CLBlast performs on your device. Would be nice to share the tuning results if you manage to run them.

**Comment by CNugteren** [comment] 2018-01-29 18:50
Closing this since no more updates. CLBlast should be compatible with OpenCL 1.1 embedded profile as well.

**Comment by simobrazz** [comment] 2018-03-22 13:50
Hi @CNugteren 

Sorry for the very late response but nothing new since a couple of days ago. The fact is that Vivante has released the new Vivante GC2000 driver (6.2.2.p0) and CLBlast could work. 

I don't now if CLBlast definitively does not supports OpeCL EP 1.1.

In attachments some outputs of CLBlast sample programs.

Thanks for any help.

Simone

[clblast_vivante_gc2000.tar.gz](https://github.com/CNugteren/CLBlast/files/1837759/clblast_vivante_gc2000.tar.gz)

**Comment by sivagnanamn** [comment] 2018-03-22 13:53
@simobrazz I've used CLBlast with OpenCL 1.1 without any issues. I've used it pre-dominantly only for GEMM operation.

**Comment by CNugteren** [comment] 2018-03-22 14:45
@sivagnanamn He is talking about OpenCL Embedded Profile, not regular OpenCL 1.1.

I see some kernel compilation errors in your logs. I'll take a look at them and see whether they are easy to fix.

**Comment by sivagnanamn** [comment] 2018-03-22 14:48
@CNugteren Yes, I meant OpenCL 1.1 Embedded profile only. The board board that I was using supports only OpenCL 1.1 & all the tuning results that I've shared so far on Adreno 330 are with OpenCL 1.1 Embedded profile only.

**Comment by simobrazz** [comment] 2018-03-22 15:27
@CNugteren If possible I would like to help you, I'm no expert on OpenCL but let me know for tests etc!

@sivagnanamn Happy to hear that in some cases CLBlast works with OpenCL EP. Did you solve any issue during the first steps with OpenCL EP or it just worked perfectly? Btw I think that Qualcomm supports their GPU better than Vivante with their own.

**Comment by CNugteren** [comment] 2018-03-22 19:13
OK, so most probably this is not an issue with CLBlast and OpenCL 1.1 EP, but more a limitation of the Vivante compiler. I'll take a look at the logs and see if can change the code to make it work with Vivante.

**Comment by mirh** [comment] 2018-03-22 19:59
There are [known issues](https://patchwork.openembedded.org/patch/145109/) on their part for CL. 
To be already allegedly corrected in the next release.

**Comment by CNugteren** [comment] 2018-03-22 20:17
I see some errors:
```
(1246:0) : error : require an integer or floating-point typed expression
(1250:0) : error : require an integer or floating-point typed expression
(1277:0) : error : require an integer or floating-point typed expression
(1281:0) : error : require an integer or floating-point typed expression
(1717:0) : error : function: 'StoreResultsDirect' hasn't the corresponding declaration
(1794:0) : error : function: 'StoreResultsChecked' hasn't the corresponding declaration
(2191:0) : error : require a matching typed expression
(2426:0) : error : function: 'StoreResults' hasn't the corresponding declaration
```
The 3 functions starting with `StoreResults` are actually the only ones in the whole CLBlast code that take an array as argument, e.g. `real cpd[NWID * MWID]`. I can simply move the loops within those functions outside to avoid this. I have done this recently for other functions as well (for other reasons), so I don't mind doing that. I'll do that today or tomorrow.

The other errors are a bit more tricky since I don't know which line they correspond to. Could you be so kind to run the `clblast_sample_sgemm` example again, but now with `printf("\n%s\n", kernel_string.c_str());` at line 90 of `/src/utilities/compile.cpp`? And then copy that to a file and share it here, so we can see what lines they refer to.

**Comment by sivagnanamn** [comment] 2018-03-23 00:33
> Did you solve any issue during the first steps with OpenCL EP or it just worked perfectly?

@simobrazz CLBlast worked perfectly out-of-the-box on Qualcomm's OpenCL 1.1 Embedded profile. I didn't have to make any hacks.

**Comment by simobrazz** [comment] 2018-03-23 08:52
@CNugteren In attachment the output from `clblast_sample_sgemm`.

[cblast_sample_sgemm.txt](https://github.com/CNugteren/CLBlast/files/1840760/cblast_sample_sgemm.txt)

**Comment by CNugteren** [comment] 2018-03-23 17:18
@simobrazz Thanks! Unfortunately, it doesn't correspond properly it seems, but my guess is that these issues:
```
(1492:0) : error : require an integer or floating-point typed expression
(1496:0) : error : require an integer or floating-point typed expression
(1523:0) : error : require an integer or floating-point typed expression
(1527:0) : error : require an integer or floating-point typed expression
```
originate from:
```
(1491)        Multiply(result, alpha, cpd[_ni * MWID + _mi]);
(1495)        AXPBY(result, alpha, cpd[_ni * MWID + _mi], beta, cgm[c_index + c_offset]);
(1520)          Multiply(result, alpha, cpd[_ni * MWID + _mi]);
(1524)          AXPBY(result, alpha, cpd[_ni * MWID + _mi], beta, cgm[c_index + c_offset]);
`` `
I'll investigate.

**Comment by CNugteren** [comment] 2018-03-23 19:32
Could you check out the `CLBlast-227-vivante-compiler-errors` branch and run the `clblast_sample_sgemm` example again? Hopefully at least some of the errors should be solved.

**Comment by simobrazz** [comment] 2018-03-25 00:24
@CNugteren On the `CLBlast-227-vivante-compiler-errors` branch the output of `clblast_sample_sgemm`  is this:

```
CLBlast: OpenCL error: clCreateKernel: -5
Completed SGEMM in 51123.887 ms with status -5
```

:-(

**Comment by CNugteren** [comment] 2018-03-25 10:07
OK, thanks for trying. It might mean that the issue is resolved: earlier on you had OpenCL error status -11 which means a failed compilation, now you have -5 which means out-of-resources. So I'm guessing perhaps you are running out of DRAM on your device? What happens if you make m/n/k smaller, say 16 each?

I would suggest you also try to run the CLBlast test programs (see [here for instructions](https://github.com/CNugteren/CLBlast/blob/master/doc/testing.md)) and try to run those, and report which ones fail/pass. The sample programs are not meant for this purpose of course.

**Comment by simobrazz** [comment] 2018-03-26 12:13
@CNugteren `What happens if you make m/n/k smaller, say 16 each?` How can I try this?

In attachment the results from the test programs (I used CBLAS as reference). Too many errors of type "Unsopported precions"..

[results_alltests.txt](https://github.com/CNugteren/CLBlast/files/1847680/results_alltests.txt)

**Comment by CNugteren** [comment] 2018-03-26 15:44
Just modify the sizes in the sample code, it's a one file sample, shouldn't be too difficult to find m/n/k values?

As for the tests, unsupported precision is not an error. Maybe you can rerun it with `make test` or `ctest` and report that output instead?

**Comment by simobrazz** [comment] 2018-03-29 15:20
> Just modify the sizes in the sample code, it's a one file sample, shouldn't be too difficult to find m/n/k values?

Sorry for this stupid question. However, the `clblast_sample_sgemm` with m=n=k=16 returns the same out-of-resources error (-5).

I tried to `make test` but after 2 hours of processing without any results from the `clblast_test_xsbmv` routine I stopped the test. In attachment the outputs from `make test` and other routines which have not passed the test.

[clblast_sample_sgemm.txt](https://github.com/CNugteren/CLBlast/files/1860717/clblast_sample_sgemm.txt)
[clblast_test_xaxpy.txt](https://github.com/CNugteren/CLBlast/files/1860698/clblast_test_xaxpy.txt)
[clblast_test_xgemm.txt](https://github.com/CNugteren/CLBlast/files/1860699/clblast_test_xgemm.txt)
[clblast_test_xgemv.txt](https://github.com/CNugteren/CLBlast/files/1860700/clblast_test_xgemv.txt)
[clblast_test_xhbmv.txt](https://github.com/CNugteren/CLBlast/files/1860701/clblast_test_xhbmv.txt)
[make_test_res.txt](https://github.com/CNugteren/CLBlast/files/1860691/make_test_res.txt)

**Comment by CNugteren** [comment] 2018-03-29 19:14
OK, thanks for trying with the smaller size. Something else must be going on then... I have done a quick search online, and found [someone with the same GPU as you](https://laanwj.github.io/2013/3/12/opencl-on-i-mx6). He mentions that `CL_OUT_OF_RESOURCES` (-5) can also occur when compiling a kernel that is too large for the kernel memory of your device. That could well be the case, because the GEMM kernel in CLBlast is quite large. To solve this, I would suggest to try to run the clblast tuner for GEMM and see if can find a few valid configurations.

About the tests: thanks. And most probably something is going wrong with the SBMV test. In terms of failures, it doesn't look too bad so far: AXPY fails only in complex precision, so this could be solved by tuning I guess. And GEMV fails only in a few case, again with the -5 error, so that should also be solvable with tuning (or changing the parameters) in theory.

Let's focus again on the -5 error by running `clblast_tuner_xgemm`, perhaps with a smaller m/n/k value in case it takes too long on your small device.

**Comment by simobrazz** [comment] 2018-03-30 14:05
@CNugteren In attachment the results from the auto-tuners xaxpy, xgemv and xgemm. 

It seems that there are many kernel configurations that could be correctly compiled.
For example the best xgemm parameters are: 

> "best_parameters": "KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=16 NDIMB=8 NDIMC=8 NWG=16 PRECISION=32 SA=0 SB=0 STRM=1 STRN=1 VWM=1 VWN=1"

But when I rerun `clblast_sample_sgemm` with m=16 n=k=8 the result is always [-5]. What I'm doing wrong? It shouldn't work?

[auto-tuners.zip](https://github.com/CNugteren/CLBlast/files/1863741/auto-tuners.zip)

**Comment by CNugteren** [comment] 2018-03-30 14:56
Thanks!

Just to be sure: after tuning, have you re-compiled the library with the new settings, e.g. after running the Python script as [described here](https://github.com/CNugteren/CLBlast/blob/master/doc/tuning.md#using-the-tuning-results)?

Next, and I'm sorry I forgot to mention this earlier, the GEMM routine uses multiple kernels. So it can be any of them (you can find out by passing `-DVERBOSE=ON` to CMake, but not needed perse). Best to tune for all the kernels that could be used within GEMM, as listed [here in the table](https://github.com/CNugteren/CLBlast/blob/master/doc/tuning.md#which-kernels-are-used-for-which-routines).

**Comment by simobrazz** [comment] 2018-04-03 13:52
Following your suggestions I re-compiled the library with the new settings.

Some notes:
- The `clblast_tuner_xaxpy` falls in infinite loop when testing for 3232 precision
- No result match found for the tuner `clblast_tuner_xgemm_direct`

The `clblast_tuner_routine_xgemm` seems to confirm the latest note. Indeed only the in-direct method works.

I tried again the `clblast_sample_sgemm` with the new settings and n=m=k=8 but the result is always -5! What I'm doing wrong?

[tuning.zip](https://github.com/CNugteren/CLBlast/files/1871670/tuning.zip)

**Comment by CNugteren** [comment] 2018-04-03 13:56
Too bad :( What could be tried now perhaps is to re-compile with `-DVERBOSE=ON` and see what output you get when running the sample. At least then we should know which kernel is causing the issue.

**Comment by simobrazz** [comment] 2018-04-05 13:43
In attachment the results from all tuners and samples re-compiled with the option `-DVERBOSE=ON`.

It seems that also the `clblast_tuner_xgemm_direct` falls in out-of-resources (-5).

Can you understand from the debug information which routine fails for the `clblast_sample_sgemm`? The useful information seems `GEMM_Copy_16_8_4_1_Pad_8_8_1_1_Transpose_4_0_0_4_Padtranspose_1_8_1_Xgemm_32_2_8_8_32_8_8_32_0_0_0_0_4_4_XgemmDirect_2_8_8_8_8_1_1_1_2_16_GemmRoutine_768` but I'm not able to interpret it.

[samples.zip](https://github.com/CNugteren/CLBlast/files/1880215/samples.zip)
[tuning.zip](https://github.com/CNugteren/CLBlast/files/1880216/tuning.zip)

Thanks again for the support!

**Comment by CNugteren** [comment] 2018-04-05 17:32
So it seems to be what I mentioned before: the -5 error is caused by the fact that your Vivante OpenCL doesn't allow kernels larger than a specific size (see also [here](https://laanwj.github.io/2013/3/12/opencl-on-i-mx6)). That's unfortunate, because CLBlast kernels are quite big and are also compiled all together, so that might make it even worse.

So the regular GEMM kernel at least has some options that work. The GEMM direct kernel doesn't even have the default option working, because it is just too big. We could try to circumvent this somehow, but not sure how sustainable this is. I also that your device is super super slow, running the tuners must have taken quite some time... I have seen ARM and Qualcomm GPUs reaching ~10-100GFLOPS, but you seem to achieve only 0.7 GFLOPS (note that you can also run the tuners with smaller matrices to speed them up).

You could try to make the default GEMM direct kernel even smaller by changing [this](https://github.com/CNugteren/CLBlast/blob/master/src/kernels/level3/xgemm_direct_part1.opencl#L25) and subsequent occurences of the value 8 for some tuning parmeters (5x) to lower, e.g. 4 or 2 and try the tuner again? Then maybe also lower the options explored [in the tuner, e.g. here](https://github.com/CNugteren/CLBlast/blob/master/src/tuning/kernels/xgemm_direct.hpp#L76).

I'm not sure it is easy to support this corner case in CLBlast. What do you think?

**Comment by mirh** [comment] 2018-04-09 10:29
Hw is supposed to just support properly the api. 
NNs then build over it. 

And as I was saying above, they had indeed "anticipated" problems with opencl. 
Maybe you could ask on their community website if they have any news on "6.2.3"?

**Comment by CNugteren** [comment] 2018-04-10 07:33
@mirh: No, that's not the issue. The issue is that  Vivante OpenCL doesn't allow kernels larger than a specific size (see also [here](https://laanwj.github.io/2013/3/12/opencl-on-i-mx6)). That's according to the spec, but quite a tricky limitation, since I don't know any other platforms that have issues with the size of the CLBlast kernels, and thus, these kernels are not optimised for size. For Vivante I would have to do that, which is possible I guess (as I remark above, there are things still to try). However, that would probably also not lead to very high performance.

**Comment by mirh** [comment] 2018-04-10 10:26
It could be asked them to increase that too, if they are even aware to begin with.

**Comment by CNugteren** [comment] 2018-04-10 14:26
I guess that's a hardware limitation w.r.t. the instruction cache size.

**Comment by simobrazz** [comment] 2018-04-11 08:59
[Here](https://community.nxp.com/thread/305326) another post that confirms hardware limitations.

**Comment by CNugteren** [comment] 2018-04-11 12:09
From what I understand that drivers is not available? In any case, always good to have the latest drivers, but not sure if that would resolve anything.

What you can still do if you want to spent time on this is do what I suggested earlier:
> You could try to make the default GEMM direct kernel even smaller by changing [this](https://github.com/CNugteren/CLBlast/blob/master/src/kernels/level3/xgemm_direct_part1.opencl#L25) and subsequent occurences of the value 8 for some tuning parmeters (5x) to lower, e.g. 4 or 2 and try the tuner again? Then maybe also lower the options explored [in the tuner, e.g. here](https://github.com/CNugteren/CLBlast/blob/master/src/tuning/kernels/xgemm_direct.hpp#L76).

This would require digging in a bit deeper and learning what these parameters mean I guess. I could also make a branch for you where this is set-up as I suggested above, but perhaps you can try first?

**Comment by simobrazz** [comment] 2018-04-11 12:36
> From what I understand that drivers is not available?
The latest driver is available on the latest Yocto release of NXP, so I would like to try it. Until now I've tried with the 6.2.2p0 driver version and Debian Release.

> This would require digging in a bit deeper and learning what these parameters mean I guess. I could also make a branch for you where this is set-up as I suggested above, but perhaps you can try first?

Ok I will try these settings!

PS: As Deep Learning is the topic of my research project, I'm interested to learn more about CLBlast and GPUs in general. Btw I'm at the beginning with HW architectures and OpenCL libraries perhaps I have to work hard on it!

**Comment by CNugteren** [comment] 2018-05-10 17:11
OK, don't worry, and thanks for the update. Let me know if you need any help.

**Comment by CNugteren** [comment] 2018-11-07 18:56
Closing this as there isn't much activity, not much I can do either. Hopefully Vivante will work on accepting larger kernels in future drivers / hardware. Otherwise the solution would be to set the tuners to a limited small set of parameters, hoping that they do fit.

Closing for now, feel free to re-open.

**Closed by CNugteren** 2018-11-07 18:56 UTC
Labels: question
