### ISSUE TITLE
Half precision tests failing

### ISSUE THREAD

**Issue by psyhtest** [CNugteren/CLBlast#102] opened 2016-09-26 09:15 UTC
While testing CLBlast on an Odroid-XU3 platform with the Mali OpenCL driver v10.0 against clBLAS v2.10, I found that the only failures were due to a half precision test (see the attached [log](https://github.com/CNugteren/CLBlast/files/492664/odroid-xu3.tst.txt)). Therefore, I propose to increase the error margins for half precision tests.

**Comment by psyhtest** [comment] 2016-09-26 11:58
My first rough 
[go](https://github.com/CNugteren/CLBlast/files/492915/half_error_margins.1.patch.txt) at solving this leads to
[linking errors](https://github.com/CNugteren/CLBlast/files/493000/half_error_margins.1.log.txt).

**Comment by psyhtest** [comment] 2016-09-26 12:00
My second (not only rought but also more verbose) [go](https://github.com/CNugteren/CLBlast/files/493003/half_error_margins.2.patch.txt) results in the [same linking errors](https://github.com/CNugteren/CLBlast/files/493009/half_error_margins.2.log.txt).

**Comment by psyhtest** [comment] 2016-09-26 12:07
I have no idea why the error margin constants defined inside the templated `Tester` class cannot be found, as the class should be compiled for the `<double2, double>` and `<float2, float2>` types that fail:

```
// Compiles the templated class
template class Tester<half, half>;
template class Tester<float, float>;
template class Tester<double, double>;
template class Tester<float2, float2>;
template class Tester<double2, double2>;
template class Tester<float2, float>;
template class Tester<double2, double>;
```

But then I've never claimed that I completely understand C++ templates...

**Comment by CNugteren** [comment] 2016-09-26 18:46
I think it is a good idea to have separate error margins for different data-types. That said, it is not so easy to implement in the current form. I think your linker errors are because you didn't realize that the functions which call `TestSimilarity` are actually specializations of that function itself. Perhaps not the best design.

Here is a solution that creates a separate `TestSimilarityNear` function, and can thus also accept different error margins:
https://gist.github.com/CNugteren/fcef4b8867ece1469c8aac3019d341ee
Is this what you had in mind? I will commit it once you've tested it.

**Comment by psyhtest** [comment] 2016-09-27 12:01
@CNugteren Thanks! Your solution is much simpler and actually works :)

I've tried to test it but it's turned out to be non-trivial. 

First,  I made three builds with the relative error set at 0.025 (default), 0.050 and 0.075, expecting to see fewer failures when increasing the error margin. However, I got:
```
$ cat odroid-xu3.re-0.025.txt odroid-xu3.re-0.050.txt odroid-xu3.re-0.075.1.txt  | grep "[^0] test(s) failed"
   162 test(s) failed
   206 test(s) failed
   154 test(s) failed
```
Then, I rerun the last build five times with the number of failing tests fluctuating:
```
$ chronos_downloads $ cat odroid-xu3.re-0.075.?.txt | grep "[^0] test(s) failed"
   154 test(s) failed
   1 test(s) failed
   162 test(s) failed
   158 test(s) failed
   164 test(s) failed
```
(The second run didn't even perform the same number of tests as the other four.)

This suggests that a different random seed is used each time, which of course hampers reproducibility. Can you confirm that?

Also, the error rate sometimes exceeds 30% for larger matrices. This may represent genuine issues or just loss of precision. Perhaps not just one but a vector of margin values is needed to ensure no genuine failures. This vector may need to be found empirically for each new platform supporting half precision...

I'm attaching the logs here:

[odroid-xu3.re-0.075.5.txt](https://github.com/CNugteren/CLBlast/files/495391/odroid-xu3.re-0.075.5.txt)
[odroid-xu3.re-0.075.4.txt](https://github.com/CNugteren/CLBlast/files/495390/odroid-xu3.re-0.075.4.txt)
[odroid-xu3.re-0.075.3.txt](https://github.com/CNugteren/CLBlast/files/495392/odroid-xu3.re-0.075.3.txt)
[odroid-xu3.re-0.075.2.txt](https://github.com/CNugteren/CLBlast/files/495394/odroid-xu3.re-0.075.2.txt)
[odroid-xu3.re-0.075.1.txt](https://github.com/CNugteren/CLBlast/files/495393/odroid-xu3.re-0.075.1.txt)
[odroid-xu3.re-0.050.txt](https://github.com/CNugteren/CLBlast/files/495381/odroid-xu3.re-0.050.txt)
[odroid-xu3.re-0.025.txt](https://github.com/CNugteren/CLBlast/files/495380/odroid-xu3.re-0.025.txt)

**Comment by CNugteren** [comment] 2016-09-27 18:04
Thanks for testing. I have already committed the patch I mentioned previously - we can tune the actual settings later.

About the random results: you are right. I checked the code and all vectors contain proper random values. I've changed that now to contain a fixed seed: tests should be reproducible now. Can you re-run them?

About the failures: Yes, it could very well be that there is something wrong with half precision within the library. I haven't tested much (due to a lack of devices), but I couldn't make everything work on the Intel Beignet devices I tested on. As a test you can run the half-precision GEMM tuner on your device. Perhaps some configurations are invalid for fp16? The tuners also test for errors, so that would perhaps be the starting point. Note also that there are no HGEMM tuning results for Mali in the database yet, so it uses the 'defaults', which might also be causing issues.

**Comment by psyhtest** [comment] 2016-09-28 09:34
Thanks! The tests are now both reproducible and consistent:
```
549 20160927 $ cat odroid-xu3.re-0.050.?.txt | grep "[^0] test(s) failed"
   212 test(s) failed
   212 test(s) failed
   212 test(s) failed
550 20160927 $ cat odroid-xu3.re-0.100.?.txt | grep "[^0] test(s) failed"
   122 test(s) failed
   122 test(s) failed
   122 test(s) failed
```
In this example, increasing the relative error margin from 0.050 to 0.100 resulted in making 90 tests pass.

I'm now running some experiments to see what error margins should be used (assuming the library is correct of course).

[odroid-xu3.re-0.100.1.txt](https://github.com/CNugteren/CLBlast/files/497620/odroid-xu3.re-0.100.1.txt)
[odroid-xu3.re-0.050.2.txt](https://github.com/CNugteren/CLBlast/files/497624/odroid-xu3.re-0.050.2.txt)
[odroid-xu3.re-0.100.2.txt](https://github.com/CNugteren/CLBlast/files/497622/odroid-xu3.re-0.100.2.txt)
[odroid-xu3.re-0.050.3.txt](https://github.com/CNugteren/CLBlast/files/497625/odroid-xu3.re-0.050.3.txt)
[odroid-xu3.re-0.100.3.txt](https://github.com/CNugteren/CLBlast/files/497621/odroid-xu3.re-0.100.3.txt)
[odroid-xu3.re-0.050.1.txt](https://github.com/CNugteren/CLBlast/files/497623/odroid-xu3.re-0.050.1.txt)

**Comment by psyhtest** [comment] 2016-09-28 11:39
I've done some more runs, this time playing with both the relative error (re) and absolute error (ae) margins. The results are pretty interesting!

```
-rw-r--r-- 1 anton dvdt  81574 Sep 28 11:31 odroid-xu3.re-0.050.ae-0.100.1.txt
-rw-r--r-- 1 anton dvdt  72914 Sep 28 11:31 odroid-xu3.re-0.100.ae-0.050.1.txt
-rw-r--r-- 1 anton dvdt  80224 Sep 28 11:31 odroid-xu3.re-0.100.ae-0.100.1.txt
-rw-r--r-- 1 anton dvdt  79614 Sep 28 11:31 odroid-xu3.re-0.100.ae-0.333.1.txt
-rw-r--r-- 1 anton dvdt  78856 Sep 28 11:31 odroid-xu3.re-0.100.ae-0.500.1.txt
-rw-r--r-- 1 anton dvdt  78552 Sep 28 11:31 odroid-xu3.re-0.100.ae-0.666.1.txt
-rw-r--r-- 1 anton dvdt  77947 Sep 28 11:31 odroid-xu3.re-0.100.ae-0.999.1.txt
-rw-r--r-- 1 anton dvdt  79014 Sep 28 11:31 odroid-xu3.re-0.200.ae-0.200.1.txt
-rw-r--r-- 1 anton dvdt  78406 Sep 28 11:31 odroid-xu3.re-0.200.ae-0.333.1.txt
-rw-r--r-- 1 anton dvdt  78084 Sep 28 11:31 odroid-xu3.re-0.200.ae-0.500.1.txt
-rw-r--r-- 1 anton dvdt  77931 Sep 28 11:31 odroid-xu3.re-0.200.ae-0.666.1.txt
-rw-r--r-- 1 anton dvdt  77475 Sep 28 11:31 odroid-xu3.re-0.200.ae-0.999.1.txt
-rw-r--r-- 1 anton dvdt  77779 Sep 28 11:31 odroid-xu3.re-0.333.ae-0.333.1.txt
-rw-r--r-- 1 anton dvdt  77723 Sep 28 11:31 odroid-xu3.re-0.333.ae-0.500.1.txt
-rw-r--r-- 1 anton dvdt  77779 Sep 28 11:31 odroid-xu3.re-0.333.ae-0.666.1.txt
-rw-r--r-- 1 anton dvdt 180302 Sep 28 11:31 odroid-xu3.re-0.333.ae-0.999.1.txt
-rw-r--r-- 1 anton dvdt 239406 Sep 28 11:31 odroid-xu3.re-0.500.ae-0.999.1.txt
```
All but the last two experiments failed in `HGEMV` (the log file size ~80KB). The penultimate one reached `HSYMV`. The ultimate one reached `HTRMV`.

```
561 20160928 $ cat odroid-xu3.*.1.txt | grep "\([0-9]\{2,\}\|[1-9]\) test(s) failed"
   56 test(s) failed
   62 test(s) failed
   38 test(s) failed
   30 test(s) failed
   20 test(s) failed
   16 test(s) failed
   8 test(s) failed
   22 test(s) failed
   14 test(s) failed
   10 test(s) failed
   8 test(s) failed
   2 test(s) failed
   6 test(s) failed
   6 test(s) failed
   6 test(s) failed
   2 test(s) failed
   144 test(s) failed
```

[odroid-xu3.re-0.200.ae-0.200.1.txt](https://github.com/CNugteren/CLBlast/files/497887/odroid-xu3.re-0.200.ae-0.200.1.txt)
[odroid-xu3.re-0.200.ae-0.666.1.txt](https://github.com/CNugteren/CLBlast/files/497890/odroid-xu3.re-0.200.ae-0.666.1.txt)
[odroid-xu3.re-0.100.ae-0.500.1.txt](https://github.com/CNugteren/CLBlast/files/497892/odroid-xu3.re-0.100.ae-0.500.1.txt)
[odroid-xu3.re-0.100.ae-0.999.1.txt](https://github.com/CNugteren/CLBlast/files/497889/odroid-xu3.re-0.100.ae-0.999.1.txt)
[odroid-xu3.re-0.100.ae-0.666.1.txt](https://github.com/CNugteren/CLBlast/files/497888/odroid-xu3.re-0.100.ae-0.666.1.txt)
[odroid-xu3.re-0.333.ae-0.333.1.txt](https://github.com/CNugteren/CLBlast/files/497891/odroid-xu3.re-0.333.ae-0.333.1.txt)
[odroid-xu3.re-0.050.ae-0.100.1.txt](https://github.com/CNugteren/CLBlast/files/497898/odroid-xu3.re-0.050.ae-0.100.1.txt)
[odroid-xu3.re-0.333.ae-0.999.1.txt](https://github.com/CNugteren/CLBlast/files/497893/odroid-xu3.re-0.333.ae-0.999.1.txt)
[odroid-xu3.re-0.333.ae-0.666.1.txt](https://github.com/CNugteren/CLBlast/files/497897/odroid-xu3.re-0.333.ae-0.666.1.txt)
[odroid-xu3.re-0.200.ae-0.999.1.txt](https://github.com/CNugteren/CLBlast/files/497895/odroid-xu3.re-0.200.ae-0.999.1.txt)
[odroid-xu3.re-0.200.ae-0.333.1.txt](https://github.com/CNugteren/CLBlast/files/497896/odroid-xu3.re-0.200.ae-0.333.1.txt)
[odroid-xu3.re-0.100.ae-0.333.1.txt](https://github.com/CNugteren/CLBlast/files/497894/odroid-xu3.re-0.100.ae-0.333.1.txt)
[odroid-xu3.re-0.100.ae-0.050.1.txt](https://github.com/CNugteren/CLBlast/files/497900/odroid-xu3.re-0.100.ae-0.050.1.txt)
[odroid-xu3.re-0.500.ae-0.999.1.txt](https://github.com/CNugteren/CLBlast/files/497899/odroid-xu3.re-0.500.ae-0.999.1.txt)
[odroid-xu3.re-0.200.ae-0.500.1.txt](https://github.com/CNugteren/CLBlast/files/497903/odroid-xu3.re-0.200.ae-0.500.1.txt)
[odroid-xu3.re-0.100.ae-0.100.1.txt](https://github.com/CNugteren/CLBlast/files/497902/odroid-xu3.re-0.100.ae-0.100.1.txt)
[odroid-xu3.re-0.333.ae-0.500.1.txt](https://github.com/CNugteren/CLBlast/files/497901/odroid-xu3.re-0.333.ae-0.500.1.txt)

**Comment by psyhtest** [comment] 2016-09-28 11:51
Based on this I would say that the sweetspot for `HGEMV` would be either `odroid-xu3.re-0.200.ae-0.500.1.txt` (10 failures) and `odroid-xu3.re-0.333.ae-0.333.1.txt` (6 failures), depending on whether you try to minimise the relative error or the absolute error.

Apart from the routine under test and precision, the margins may depend on the platform or random seed. We could actually write scripts to determine sweetspots, and complain when they are too suspicious (e.g. the relative error of 0.999 would be very suspicious) or outside of margins determined for other platforms. Of course, we would need something like [Collective Knowledge](http://cknowledge.org) to accumulate such growing body of knowledge... :)

**Comment by CNugteren** [comment] 2016-09-29 06:40
I will look into it this weekend. But did you know about the `-verbose` option for the tests? That way you can see what the actual values are (reference vs expected) as see if the differences should be considered acceptable.

**Comment by CNugteren** [comment] 2016-10-05 19:31
I did some additional tests on my own FP16 device (Intel Skylake GPU on Intel Beignet). However, I can still not make it work reliably (both tuners & tests fail a lot), even after upgrading to the latest Beignet, Intel drivers, Linux kernel, etc. However, I have an idea what could be causing the issue.

In line 46 of `src/kernels/common.opencl` I would like to write `#define ZERO 0.0h`. However, I had to omit the 'h' literal because Beignet would complain with `error: invalid suffix 'h' on floating constant`. However, I see now that the compiler is right, because this 'h' extension is only part of OpenCL 1.2 or newer (https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/cl_khr_fp16.html) and not of OpenCL 1.1 (https://www.khronos.org/registry/cl/sdk/1.1/docs/man/xhtml/cl_khr_fp16.html).

If that's the indeed the case and I understand the specifications correctly, perhaps setting a half-precision register variable to zero (or some other constant) is not supported before OpenCL 1.2? In that case perhaps the values 0 and 1 should be passed in as arguments or converted from float somehow. Do you think this might be causing the issue? If your device does support OpenCL 1.2, could you perhaps test it with the 'h' added to the half-precision constants?

And perhaps I am also doing comparisons on half-precision, which is only supported from OpenCL 1.2 onwards (`The relational, equality, logical and logical unary operators can be used with half scalar and halfn vector types and shall produce a scalar int and vector shortn result respectively.`) and apparently return an integer. I'll have to double check this.

**Comment by blueberry** [comment] 2016-10-05 19:44
Couldn't you use a cast or some bit manipulation to set that zero (I didn't read the code, so excuse me if I'm talking nonsense).

**Comment by CNugteren** [comment] 2016-11-27 12:44
I have recently fixed some bugs in CLBlast, relaxed the error margins for half-precision, and updated to the latest version of Beignet. My remarks above are probably not true. After all these changes, most of the half-precision tests pass on my Intel Skylake GPU. There are still occasional errors in the FP16 tests though, sometimes half-precision can lead to quite large errors due to accumulation of multiple small errors. Not sure how to handle that nicely.

Perhaps you can try again and see what the current status is?

**Comment by CNugteren** [comment] 2017-02-10 17:53
@psyhtest, @intelfx, or anyone else with access to ARM Mali: any change you can re-run the tests again and see what the current status is? Thanks!

**Comment by intelfx** [comment] 2017-02-10 20:22
@CNugteren I'm building new CLBlast on @psyhtest's Mali board right now :) distcc keeps failing me though.

**Comment by intelfx** [comment] 2017-02-10 22:04
@CNugteren There are still some test failures (not many) in `-full_test 1` mode. Re-running with `-verbose 1` now.

**Comment by intelfx** [comment] 2017-02-10 22:35
Here is the log: [2017-02-10 CLBlast HGEMM on Mali.log](https://intelfx.name/files/2017-02-10%20CLBlast%20HGEMM%20on%20Mali.log)

**Comment by CNugteren** [comment] 2017-02-11 09:19
Thanks a lot! So HGEMM still sees occasional errors, but that could just be due to the FP16 nature. They seem to be the same as on my Intel GPU:

> After all these changes, most of the half-precision tests pass on my Intel Skylake GPU. There are still occasional errors in the FP16 tests though, sometimes half-precision can lead to quite large errors due to accumulation of multiple small errors. Not sure how to handle that nicely.

Did you run other tests as well (e.g. with CTest)? I think earlier on other routines had more serious issues. If other tests run fine (or similarly occasionally report a small error), then I can close this issue.

**Comment by intelfx** [comment] 2017-02-11 10:19
Hm. Yes, I should've run the rest.

```
76% tests passed, 10 tests failed out of 41

Total Test time (real) = 709.51 sec

The following tests FAILED:
         10 - clblast_test_xamax (Failed)
         11 - clblast_test_xgemv (Failed)
         16 - clblast_test_xsymv (Failed)
         18 - clblast_test_xspmv (Failed)
         19 - clblast_test_xtrmv (Failed)
         20 - clblast_test_xtbmv (Failed)
         21 - clblast_test_xtpmv (Failed)
         34 - clblast_test_xsymm (Failed)
         38 - clblast_test_xsyr2k (Failed)
         40 - clblast_test_xtrmm (Failed)
Errors while running CTest
```

**Comment by CNugteren** [comment] 2017-02-27 20:53
I fixed bugs in the HTBMV/HTPMV/HTRMV/HSYR2K/HTRMM routines. That should hopefully fix some of those tests. In other cases I saw small errors in only a few values compared to single-precision, so I included a check an L2 error check. That should filter out small mistakes in other tests I guess.

On my system (Intel Beignet + Skylake GPU) all half-precision tests now pass. Could you re-run the tests again (`ctest`), and for those that stil don't pass, could you run them individually in verbose-mode (e.g. `clblast_test_xamax -verbose`)? Thanks!

**Comment by CNugteren** [comment] 2017-05-07 17:03
I verified myself now on an ARM Mali system and all the tests now pass except for `xamax`. That turned out to be a small bug in the test framework, not in the actual routine. So I'm considering this issue resolved now.

**Closed by CNugteren** 2017-05-07 17:03 UTC

**Comment by psyhtest** [comment] 2017-05-08 12:48
Good stuff - many thanks!
