### ISSUE TITLE
python ../scripts/database/database.py . .. error

### ISSUE THREAD

**Issue by haolongzhangm** [CNugteren/CLBlast#219] opened 2017-11-20 08:33 UTC
1: download database.json; put to scripts/database/
2:run clblast_tuner_copy_fast  to get clblast_copy_32.json , then puth clblast_copy_32.json to scripts/
3:run command: python ../scripts/database/database.py . ..

get err result:
/CLBlast/scripts$ python ../scripts/database/database.py . ..
[database] Loading database from '../scripts/database/database.json'
[database] Processing './clblast_copy_32.json' with 0 new items
[database] Saving database to '../scripts/database/database.json'
[database] Calculating the best results per device/kernel...
[database] Calculating the default values...
[database] Producing a C++ database in '../src/database/kernels'...
Traceback (most recent call last):
  File "../scripts/database/database.py", line 154, in <module>
    main(sys.argv[1:])
  File "../scripts/database/database.py", line 148, in main
    clblast.print_cpp_database(database_best_results, cpp_database_path)
  File "/media/zhl/second/code/caffe-android-lib/CLBlast/scripts/database/database/clblast.py", line 176, in print_cpp_database
    assert len(kernel_database) == 1
AssertionError

**Comment by CNugteren** [comment] 2017-11-20 19:31
I was afraid of that... I recently changed the tuners. Thanks for reporting! Could you send me the JSON file you used? That way I'll be able to reproduce the issue and fix it. Sorry for the inconvenience. Alternatively you can go back to the 1.2.0 CLBlast stable master.

**Comment by CNugteren** [comment] 2017-11-20 20:39
I believe I fixed the issue in the latest commit in master, I was able to reproduce the issue myself. Could you re-run the Python script and see if it does work as expected now?

**Comment by haolongzhangm** [comment] 2017-11-21 01:18
1:test at master@5467c0cac55b02bda69057fe0a130379934b8edb 
database with :  curl https://raw.githubusercontent.com/CNugteren/CLBlast-database/master/database.json > database.json       (fetch the database yestoday)

2: as u commit already fixed this issue, I will pull ,then restest , then update result

**Comment by CNugteren** [comment] 2017-11-25 08:51
@haolongzhangm I do not understand your last message. Is the issue fixed with the latest version? Or do you still need to test it? Let me know, or close the issue if it is solved.

**Comment by CNugteren** [comment] 2017-12-14 20:16
I'm closing this due to inactivity. I believe it is solved anyway, if not, please re-open.

**Closed by CNugteren** 2017-12-14 20:16 UTC
Labels: bug
