### ISSUE TITLE
CLBLAST Build on Windows with Intel OpenCL/ Integrated GPU

### ISSUE THREAD

**Issue by mcwmurugan** [CNugteren/CLBlast#273] opened 2018-04-18 06:05 UTC
Did anyone try to build CLBLAST for Windows with Intel OpenCL?
I have been trying to build the InBuilt samples of Gemm with Intel OpenCL and Visual Studio2013, under OpenCL 1.2 run time on Intel(R) HD Graphics 2500. 
I am getting the following error message,

**CLBlast: Run-time error: -2041**

This is the Log Generated when tried to build with verbose option:

[DEBUG] Searching database for kernel 'Copy'
[DEBUG] Device type 'GPU'; vendor 'Intel'
[DEBUG] Device name 'Intel(R) HD Graphics 2500'; architecture ''
[DEBUG] Found architectures of vendor 'Intel' and type 'GPU'
[DEBUG] Found architectures of vendor 'default' and type 'default'

Any Ideas/Comments on this??

**Comment by CNugteren** [comment] 2018-04-18 07:11
Windows + Intel OpenCL was tested before, it should work. Perhaps this is caused by a recently introduced bug or something particular with your device.

In any case, [error -2041](https://github.com/CNugteren/CLBlast/blob/master/include/clblast.h#L109) is a CLBlast database error and shouldn't occur. I'll investigate what could have gone wrong.

**Comment by mcwmurugan** [comment] 2018-04-18 07:41
Hello CNugteren,
Can you suggest me some working commit on windows so that I can try out some samples??
Need to know whether am I doing something wrong.

Thanks

**Comment by CNugteren** [comment] 2018-04-18 09:12
I would suggest to try one of the [releases](https://github.com/CNugteren/CLBlast/releases). If the latest one doesn't work you could try a previous version. But if they also don't work you'll have to wait a bit for me to find time to look at it.

**Comment by CNugteren** [comment] 2018-04-18 19:18
The compilation instructions for Visual Studio are [in the documentation](https://github.com/CNugteren/CLBlast/blob/master/doc/installation.md#windows-compilation-from-source). The only dependency is OpenCL. Other than that it is nice if you have another CPU BLAS library installed or clBLAS.

Thanks for giving the verbose output. I also get similar output on my system, but then it continues:
```
[DEBUG] Searching database for kernel 'Copy'
[DEBUG] Device type 'GPU'; vendor 'Intel'
[DEBUG] Device name 'Intel(R) HD Graphics'; architecture ''
[DEBUG] Found architectures of vendor 'Intel' and type 'GPU'
[DEBUG] Found devices of architecture type 'default'
[DEBUG] Found parameters for device type 'default'

[DEBUG] Searching database for kernel 'Pad'
[DEBUG] Device type 'GPU'; vendor 'Intel'
[DEBUG] Device name 'Intel(R) HD Graphics'; architecture ''
[DEBUG] Found architectures of vendor 'Intel' and type 'GPU'
[DEBUG] Found devices of architecture type 'default'
[DEBUG] Found parameters for device type 'default'

[DEBUG] Searching database for kernel 'Transpose'
[DEBUG] Device type 'GPU'; vendor 'Intel'
(...)
```

So it seems to go wrong before `Found parameters ...`. Perhaps it crashes in the [`CharArrayToString` function](https://github.com/CNugteren/CLBlast/blob/master/src/database/database.cpp#L215) or the line afterwards. Both of those do some string manipulation, perhaps something that is not fully implemented correctly under VS 2013 (note that VS 2013 is not fully C++11 compatible, so things could go wrong).

You could either play with those lines I mentioned to see if you can debug it (if you are proficient with C++). Otherwise you'll have to wait a few days till I find time to boot my Windows test machine and get VS 2013 working again.

**Comment by CNugteren** [comment] 2018-04-19 19:41
Could you perhaps change [those lines (215-217)](https://github.com/CNugteren/CLBlast/blob/master/src/database/database.cpp#L215) into the following:
```
    log_debug("Searching for '" + std::string(device.name.data()) + "' (1)");
    const auto device_name = CharArrayToString(device.name);
    log_debug("Searching for '" + device_name + "' (2)");
    // Cuts off 'target_device' string at 50 since the database cuts off as well
    const auto target_device_cut_off = (target_device.length() > 50) ? target_device.substr(0, 50) : target_device;
    log_debug("Matching to '" + target_device_cut_off + "' (3)");
```
Basically just adds some log-statements. And then run again in verbose mode to see if it prints and what it prints?

**Comment by mcwmurugan** [comment] 2018-04-25 10:07
@CNugteren 
Thanks for your Quick response and sorry for the delay, caught up with few commitments. 
I tried changing those lines in database.cpp, I didn't get any additional log information, It is still the same.

In the meantime, I tried to build CLBlast with Vs2015 and VS2017. the Build is fine and I am able to run the samples and tuners. The only issue with both builds are, It crashes after exiting main() in the GEMM samples.

I investigated it further it looks like when we trying to release the program it crashes in the following line. 
[clpp11.hpp](https://github.com/CNugteren/CLBlast/blob/5d46a3193e9034ba567950f166f4ab2de326fee0/src/clpp11.hpp#L445)

**Comment by mcwmurugan** [comment] 2018-04-26 06:48
@CNugteren 
Further details on the issue with VS2013,
It looks like the database initialization is going wrong here, I checked the code in debug mode where it looks like vendor.archcitectures is empty for all kernels.
In this [line ](https://github.com/CNugteren/CLBlast/blob/5d46a3193e9034ba567950f166f4ab2de326fee0/src/database/database.cpp#L94) If you check, all kernel vendors/architecture it is empty. I guess it is the culprit.

**Comment by CNugteren** [comment] 2018-04-26 19:18
OK, thanks for trying!

I have tried myself yesterday with VS 2013 and also noticed the issue with releasing the OpenCL program, the same as you report with VS 2015 and 2017, and also the same as is reported in #203 and #199. So I just [disabled that line](https://github.com/CNugteren/CLBlast/commit/7b416c8686f7cc83c79c886e24851db33baacf80) when compiled with Visual Studio. Could you try again with the latest master of CLBlast?

About the other issue you reported with the empty database, I am not sure how to proceed. I compiled myself with VS 2013 with NVIDIA OpenCL and managed to run it successfully. But since you've got it working with VS 2015, it does seem VS 2013 related. Hmm... Are you OK with using a newer VS?

**Comment by mcwmurugan** [comment] 2018-04-27 05:33
@CNugteren  
Thanks for the quick fix and it is an amazing library. Yeah, am completely fine with newer versions of VS. If we are not bothering about VS2013, we can ignore this issue for now.

**Comment by CNugteren** [comment] 2018-04-28 08:25
OK, so I'll close this then with the note that there is still an issue with VS 2013 on your setup, but it solved when going to VS 2015 or newer. It is however not always an issue, because with my VS 2013 I can't reproduce it.

**Closed by CNugteren** 2018-04-28 08:25 UTC
Labels: bug
