### ISSUE TITLE
Memory with series of unblocked sgemm calls

### ISSUE THREAD

**Issue by newling** [CNugteren/CLBlast#185] opened 2017-08-30 15:13 UTC
Hi,

This is probably not a bug, more a limitation. Not sure if there's a solution.

In a for loop I call `CLBlastSgemm` with,
tA = yes   
tB = no   
colMaj = yes
m = 512   
n = 8    
k = 500000  
minimal lda, ldb, ldc (lda = 500000  ldb = 500000  ldc = 512)
 
CPU memory rapidly exceeds 32GB. 

I then observe either 
`CLBlast: OpenCL error: clEnqueueNDRangeKernel: -4`

or
`Memory access fault by GPU node-1 on address 0xd8a9dd000. Reason: Page not present or supervisor privilege`

I guess CLBlast is allocating workspace memory on the GPU (but not sure why CPU memory goes up)

If I change from tA = yes to tA = no, the memory consumption is greatly reduced and the loop runs to completion, which is surprising as matrix sizes are unchanged.

The above is all with the final `cl_event *` parameter to `CLBlastSgemm` set to nullptr. If instead I pass a pointer to a cl_event and then block after each gemm call with `cl_wait_for_events`, there are no problems, unsurprisingly.

Above on Fiji Nano GPU using ROCm 1.6.

Thanks.

**Comment by CNugteren** [comment] 2017-08-30 17:13
Thanks for reporting. If CLBlast leaks memory, then that should be considered a bug.

There was a whole discussion about this a while ago (#74) but all those issues were resolved. Based on your remark related to the event pointer, it seems related to the earlier mentioned issue though. Could you read through the discussion and see if there is any experiment you can do to verify the cause?

With respect to changing the transpose option: CLBlast might need to allocate GPU memory based on whether or not it needs to pre-transpose the matrix, so a difference in behaviour could be explained by the fact that more/less kernels might run. But of course it shouldn't leak any memory.

**Comment by newling** [comment] 2017-08-31 06:53
I haven't confirmed that CLBlast is leaking memory. What I thought might be happening was memory allocation for each GEMM call only to be released after GEMM is complete. As the first GEMM might only complete after the last GEMM is enqueued (when no cl_event blocking),  I thought the memory explosion might not be a "bug". 

I will look into this again. Not sure how much CPU memory cl_events require, but memory seems to get consumed very fast - I think 100 calls to GEMM is enough to "consume" 32 GB. Note that this 32 GB is an upper bound, as I'm just watching System Monitor.    

Will look into it again.

**Comment by CNugteren** [comment] 2017-08-31 18:45
OK, thanks for the clarification, I misunderstood. Then your earlier remark also fully explains everything:

> If I change from tA = yes to tA = no, the memory consumption is greatly reduced and the loop runs to completion, which is surprising as matrix sizes are unchanged.

In some cases CLBlast allocates temporary memory (equal to the size of the input and/or output buffers) to pre-transpose input or post-transpose output. The actual 'indirect' GEMM kernel doesn't handle that, it assumes a canonical input. This temporary buffer memory is probably what you see, as it can get quite big and is necessary only for specific argument (m, n, k, transpose). To know this for sure you can instrument the code manually or by compiling with `-DVERBOSE=ON`. It will give you print-messages before each kernel launch. And thus, you'll see that pre/post kernels (and thus the corresponding buffers) are not always required.

Why this is CPU memory if you are running on the GPU is a bit of a mystery, but perhaps your system starts to 'swap' to the main CPU memory?

**Comment by newling** [comment] 2017-09-01 10:28
With `-DVERBOSE=ON`  there is no additional CPU memory used and the code runs cleanly to completion. 

```
.
.
.
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 5.79 ms
[DEBUG] Running kernel 'TransposePadMatrix'
[DEBUG] Completed kernel in 0.28 ms
[DEBUG] Running kernel 'CopyPadMatrix'
[DEBUG] Completed kernel in 0.07 ms
[DEBUG] Running kernel 'Xgemm'
[DEBUG] Completed kernel in 111.30 ms
[DEBUG] Running kernel 'CopyMatrix'
```

**Comment by CNugteren** [comment] 2017-09-01 14:47
> With -DVERBOSE=ON there is no additional CPU memory used

That's because now there are event synchronisations everywhere. What I meant was to use verbose-mode to see that indeed it is not just running the `Xgemm` kernel but also some other kernels. And indeed, they show up. Try again with the other transpose options and you might not see the pre-processing and post-processing kernels.

**Comment by newling** [comment] 2017-09-04 10:02
Oh I see. 

I should check how much GPU memory is allocated with each GEMM call, and see if the CPU memory starts to increase only when this these allocations correspond to total GPU memory. Will get back on this.

**Comment by CNugteren** [comment] 2017-10-08 09:04
@newling Any updates from your side? Not sure what I can still do here for you...

**Comment by newling** [comment] 2017-10-14 18:36
Hi, sorry for the delay. I haven't done any further investigating. But I guess we know what is going on here: accumulating GPU memory allocations for each GEMM call, with (possible) spilling over onto the CPU for my particular GPU setup. So feel free to close, I can always leave a comment here if I find out something new/related.

**Comment by CNugteren** [comment] 2017-10-14 18:52
OK, thanks for the update! In that case I'll close it indeed: it's part of the design of CLBlast to allocate some extra buffers internally.

**Closed by CNugteren** 2017-10-14 18:52 UTC
