### ISSUE TITLE
SGEMM failures in CLBlast tests

### ISSUE THREAD

**Issue by hughperkins** [CNugteren/CLBlast#41] opened 2016-04-05 10:35 UTC
Two failures in SGEMM test, using `-full_test`, on NVIDIA 940M, with libopenblas installed, on ubuntu 64-bit

```
* Testing 'regular behaviour' for '1 (col-major) 1 (transposed) 0 (regular)':
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ................................................................
   ................................................................
   ................................................................
   ................................................................
   ................................................................
   ........................................::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::................
   ........................................................::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ................................................................
   ................................................................
   ................................................................
   ................................................................
   ................................................................
   ........................................::::::::::::::::::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::................
   ........................................................::::::::
   ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
   ..................::::::::::::::::::..................::::::::::
   ::::::::..................::::::::::::::::::..................::
   ::::::::::::::::..................::::::::::::::::::............
   ......::::::::::::::::::..................::::::::::::::::::....
   ..............::::::::::::::::::..................::::::::::::::
   ::::..................::::::::::::::::::..................::::::
   ::::::::::::..................::::::::::::::::::................
   ..::::::::::::::::::..................::::::::::::::::::........
   ..........::::::::::::::::::..................::::::::::::::::::
   ................................................................
   ................................................................
   ................................................................
   ................................................................
   ................................................................
   ..........................................................::::::
   :X::::::::::..................::::::::::::::::::................
   ................................................................
   ..........::::::::::::::::::..................::::::::::::::::::
   ..................::::::::::::::::::..................::::::::::
   ::::::::..................::::::::::::::::::..................::
   ::::::::::::::::..................::::::::::::::::::............
   ......::::::::::::::::::..................::::::::::::::::::....
   ..............::::::::::::::::::..................::::::::::::::
   ::::..................::::::::::::::::::..................::::::
   ::::::::::::..................::::::::::::::::::................
   ..::::::::::::::::::..................::::::::::::::::::........
   ..........::::::::::::::::::..................::::::::::::::::::
   ................................................................
   ................................................................
   ................................................................
   ................................................................
   ................................................................
   ..........................................................::::::
   :X::::::::::..................::::::::::::::::::................
   ................................................................
   ..........::::::::::::::::::..................::::::::::::::::::
   Error rate 0.2%: m=64 n=7 k=64 layout=1 transA=1 transB=0 lda=64 ldb=64 ldc=64 offa=0 offb=0 offc=0 
   Error rate 0.0%: m=64 n=64 k=64 layout=1 transA=1 transB=0 lda=64 ldb=64 ldc=64 offa=0 offb=0 offc=0 
   Pass rate 100.0%: 4606 passed / 0 skipped / 2 failed

```

blases installed:
```
 dpkg -l '*blas*' | grep ii
ii  libblas-common   1.2.20110419-10 amd64        Dependency package for all BLAS implementations
ii  libblas-dev      1.2.20110419-10 amd64        Basic Linear Algebra Subroutines 3, static library
ii  libblas3         1.2.20110419-10 amd64        Basic Linear Algebra Reference implementations, shared library
ii  libopenblas-base 0.2.14-1ubuntu1 amd64        Optimized BLAS (linear algebra) library (shared library)
ii  libopenblas-dev  0.2.14-1ubuntu1 amd64        Optimized BLAS (linear algebra) library (development files)
```

**Comment by CNugteren** [comment] 2016-04-22 00:06
I also occasionally notice such small errors. These can safely be neglected, they are related to precision issues: floating-point arithmetic is not associative, e.g. `(a+b)+c != a+(b+c)`. I will see if I can improve the testing infrastructure to not report these.

**Comment by hughperkins** [comment] 2016-04-22 06:57
I guess you can just drop the precision on the check by an order of magnitude or so?  eg maybe right now it is 1e-4, and you could drop to eg 1e-3?

**Comment by CNugteren** [comment] 2016-04-27 12:46
I have just made two commits to the `development` branch, they will be included in the next release.

* The first commit includes a new `-verbose` option to display more details about the error, actually showing the values to be able to inspect whether or not this is a real mistake or just a floating-point comparison issue.

* The second commit relaxes the absolute error margin (only used for small values) from 1e-6 to 1e-4. The relative error margin is as before, currently set to 2.5%.

I will close this issue now. If similar errors still show up, please run with `-verbose` to inspect the actual values. Thanks for reporting!

**Comment by hughperkins** [comment] 2016-04-27 16:26
Thanks!  Sounds good.  Will let you know if any issues

**Comment by psyhtest** [comment] 2016-05-04 11:46
I'm going to test the new behaviour shortly but for reference here's what I see with CLBlast 0.6.0 on Mali-T628 with the v6.0 driver:
```
* Running on OpenCL device 'Mali-T628'.
* Starting tests for the 'CGEMM' routine. Legend:
   : -> Test produced correct results
   . -> Test returned the correct error code
   X -> Test produced incorrect results
   / -> Test returned an incorrect error code
   \ -> Test not executed: OpenCL-kernel compilation error
   o -> Test not executed: Unsupported precision
* Testing 'regular behaviour' for '0 (row-major) 0 (regular) 0 (regular)':
   ::::::::....::::...:...:.......:::::::::....::::...:...:.......:
   Pass rate 100.0%: 64 passed / 0 skipped / 0 failed
* Testing 'invalid buffer sizes' for '0 (row-major) 0 (regular) 0 (regular)':
   ...........................
   Pass rate 100.0%: 27 passed / 0 skipped / 0 failed
* Testing 'regular behaviour' for '0 (row-major) 0 (regular) 1 (transposed)':
   ::::XX::......::.:.:.X.:.......:::::XX::......::.:.:.:.:.......:
   Error rate 100.0%: m=7 n=7 k=7 layout=0 transA=0 transB=1 lda=64 ldb=7 ldc=7 offa=0 offb=0 offc=0 
   Error rate 98.0%: m=7 n=7 k=7 layout=0 transA=0 transB=1 lda=64 ldb=7 ldc=64 offa=0 offb=0 offc=0 
   Error rate 99.8%: m=7 n=64 k=7 layout=0 transA=0 transB=1 lda=64 ldb=7 ldc=64 offa=0 offb=0 offc=0 
   Error rate 99.8%: m=64 n=7 k=7 layout=0 transA=0 transB=1 lda=64 ldb=7 ldc=7 offa=0 offb=0 offc=0 
   Error rate 99.6%: m=64 n=7 k=7 layout=0 transA=0 transB=1 lda=64 ldb=7 ldc=64 offa=0 offb=0 offc=0 
   Pass rate  92.2%: 59 passed / 0 skipped / 5 failed
* Testing 'invalid buffer sizes' for '0 (row-major) 0 (regular) 1 (transposed)':
   ...........................
   Pass rate 100.0%: 27 passed / 0 skipped / 0 failed
* Testing 'regular behaviour' for '0 (row-major) 0 (regular) 2 (conjugate)':
   ::::::::......::.:.:.X.:.......:::::::::......::.:.:.X.:.......:
   Error rate 0.2%: m=7 n=64 k=7 layout=0 transA=0 transB=2 lda=64 ldb=7 ldc=64 offa=0 offb=0 offc=0 
   Error rate 0.0%: m=64 n=64 k=7 layout=0 transA=0 transB=2 lda=64 ldb=7 ldc=64 offa=0 offb=0 offc=0 
   Pass rate  96.9%: 62 passed / 0 skipped / 2 failed
```

**Comment by psyhtest** [comment] 2016-05-04 12:21
With the CLBlast development branch on Mali-T628 with the v6.0 driver:
```
* Running on OpenCL device 'Mali-T628'.
* Starting tests for the 'CGEMM' routine. Legend:
   : -> Test produced correct results
   . -> Test returned the correct error code
   X -> Test produced incorrect results
   / -> Test returned an incorrect error code
   \ -> Test not executed: OpenCL-kernel compilation error
   o -> Test not executed: Unsupported precision
* Testing 'regular behaviour' for '0 (row-major) 0 (regular) 0 (regular)':
   ::::::::....::::...:...:.......:::::::::....::::...:...:.......:
   Pass rate 100.0%: 64 passed / 0 skipped / 0 failed
* Testing 'invalid buffer sizes' for '0 (row-major) 0 (regular) 0 (regular)':
   ...........................
   Pass rate 100.0%: 27 passed / 0 skipped / 0 failed
* Testing 'regular behaviour' for '0 (row-major) 0 (regular) 1 (transposed)':
   ::::XX::......::.:.:.X.:.......:::::XX::......::.:.:.:.:.......:
   Error rate 100.0%: m=7 n=7 k=7 layout=0 transA=0 transB=1 lda=64 ldb=7 ldc=7 offa=0 offb=0 offc=0 
   Error rate 100.0%: m=7 n=7 k=7 layout=0 transA=0 transB=1 lda=64 ldb=7 ldc=64 offa=0 offb=0 offc=0 
   Error rate 100.0%: m=7 n=64 k=7 layout=0 transA=0 transB=1 lda=64 ldb=7 ldc=64 offa=0 offb=0 offc=0 
   Error rate 99.6%: m=64 n=7 k=7 layout=0 transA=0 transB=1 lda=64 ldb=7 ldc=7 offa=0 offb=0 offc=0 
   Error rate 99.6%: m=64 n=7 k=7 layout=0 transA=0 transB=1 lda=64 ldb=7 ldc=64 offa=0 offb=0 offc=0 
   Pass rate  92.2%: 59 passed / 0 skipped / 5 failed
* Testing 'invalid buffer sizes' for '0 (row-major) 0 (regular) 1 (transposed)':
   ...........................
   Pass rate 100.0%: 27 passed / 0 skipped / 0 failed
* Testing 'regular behaviour' for '0 (row-major) 0 (regular) 2 (conjugate)':
   ::::::::......::.:.:.:.:.......:::::::::......::.:.:.:.:.......:
   Pass rate 100.0%: 64 passed / 0 skipped / 0 failed
```

**Comment by CNugteren** [comment] 2016-05-04 16:29
@psyhtest Are you testing against clBLAS or a regular BLAS? If you compile CLBlast without clBLAS installed it will use a CPU BLAS to test against, which might be more reliable on less common hardware such as the ARM Mali GPU. I've seen 'errors' in CLBlast occur in other cases which turned out to be errors in the reference clBLAS library.

If the errors persist when comparing against a CPU BLAS library, could you please re-run with `-verbose` and output the results? And do they only occur for the complex version of GEMM, or also with regular SGEMM?

**Comment by psyhtest** [comment] 2016-05-05 09:54
@CNugteren  This was against clBLAS. Unfortunately, I'm having issues linking against CPU BLAS on this machine as follows:

```
CMakeFiles/clblast_client_xhemm.dir/test/performance/routines/level3/xhemm.cc.o: In function `clblast::cblasXrotg(std::vector<float, std::allocator<float> >&, unsigned int, std::vector<float, std::allocator<float> >&, unsigned int, std::vector<float, std::allocator<float> >&, unsigned int, std::vector<float, std::allocator<float> >&, unsigned int)':
/data/build/lib-clblast-dev/test/wrapper_cblas.h:55: undefined reference to `cblas_srotg'
CMakeFiles/clblast_client_xhemm.dir/test/performance/routines/level3/xhemm.cc.o: In function `clblast::cblasXrotg(std::vector<double, std::allocator<double> >&, unsigned int, std::vector<double, std::allocator<double> >&, unsigned int, std::vector<double, std::allocator<double> >&, unsigned int, std::vector<double, std::allocator<double> >&, unsigned int)':
```

It's similar to issues described [here](https://bugs.launchpad.net/ubuntu/+source/binutils/+bug/993991). Perhaps changing the order of linking would fix this but I don't have time to investigate this now, sorry.

**Comment by psyhtest** [comment] 2016-05-05 09:56
@CNugteren 

The issues always happen with 5 tests in CGEMM. As a workaround for the linking failures, I disabled finding CBLAS as follows:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index d63105e..bd58c4a 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -103,7 +103,7 @@ endif()
 # and "FindCBLAS.cmake" are included.
 if(TESTS)
   find_package(clBLAS)
-  find_package(CBLAS)
+  # find_package(CBLAS)
   if(NOT CLBLAS_FOUND AND NOT CBLAS_FOUND)
     message(STATUS "Could NOT find clBLAS nor a CPU BLAS, disabling the compilation of the tests")
     set(TESTS OFF)
```
(It would be nice to have a build flag for this.)

I'll post the results shortly.

**Comment by psyhtest** [comment] 2016-05-05 10:39
[clblast.dev.xgemm.mali-t628.v6.0.txt](https://github.com/CNugteren/CLBlast/files/250268/clblast.dev.xgemm.mali-t628.v6.0.txt)

As a shameless plug, we could share test results from different platforms via [Collective Knowlededge](http:/cknowledge.org) and compare the differences to find out whether the issue is in the library, reference library, driver, etc...

**Comment by psyhtest** [comment] 2016-05-05 15:38
@CNugteren I regret posting in this issue, as stuff just keeps on coming. Could you please re-open and re-name it appropriately (if moving the later part of the discussion to a separate issue is not possible)?

Once I have managed to link against the reference C BLAS implementation (#57), I see a different pass rate for the 5 failing tests (assuming they are the same ones as above):
```
   Error rate 98.0%: m=7 n=7 k=7 layout=101 transA=111 transB=112 lda=64 ldb=7 ldc=7 offa=0 offb=0 offc=0 
   Error rate 98.0%: m=7 n=7 k=7 layout=101 transA=111 transB=112 lda=64 ldb=7 ldc=64 offa=0 offb=0 offc=0 
   Error rate 99.3%: m=7 n=64 k=7 layout=101 transA=111 transB=112 lda=64 ldb=7 ldc=64 offa=0 offb=0 offc=0 
   Error rate 99.8%: m=64 n=7 k=7 layout=101 transA=111 transB=112 lda=64 ldb=7 ldc=7 offa=0 offb=0 offc=0 
   Error rate 99.6%: m=64 n=7 k=7 layout=101 transA=111 transB=112 lda=64 ldb=7 ldc=64 offa=0 offb=0 offc=0 
   Pass rate  92.2%: 59 passed / 0 skipped / 5 failed
```
I suggest to modify the verbose mode:

1. It's not clear whether the test uses clBLAS as before or CBLAS, as it just says "reference". How is this determined?

1. It's not clear whether failures occur at the same positions, as no indices are printed. I assume that the tests use random data, so I can't compare results from two different runs to confirm that.

1. When N reference implementations are available, it would be better to compare them pairwise or use majority voting.

[clblast.dev.xgemm.mali-t628.v6.0.cblas.txt](https://github.com/CNugteren/CLBlast/files/250633/clblast.dev.xgemm.mali-t628.v6.0.cblas.txt)

**Comment by CNugteren** [comment] 2016-05-05 20:54
I am not sure how to split this issue in two, perhaps it would have been better to start in a separate issue, but that's too late now. You make some good points which I will try to improve. Note that the verbose testing mode and testing against CBLAS are new features in the development branch and are therefore not mature yet. Your suggestions:

1. If both clBLAS and a CPU BLAS are found, the tests are against the OpenCL clBLAS. This is because that allows for testing of error codes of for example invalid OpenCL memory objects and so on. Only if clBLAS is not present it will test against the CPU BLAS version, but I will implement a switch to select between them if both are possible. I will let you know when this is done.

2. You are right, verbose mode doesn't help too much right now. I'll make sure indices are printed as well.

3. Indeed, testing against multiple references would be better. But for now I think the suggestion under point 1 should be sufficient.

**Comment by psyhtest** [comment] 2016-05-06 09:11
@CNugteren 
I've manually modified `CMakeLists` to not search for clBLAS and all the tests passed against CBLAS. So it wasn't an issue with CLBlast, phew!

[clblast.dev.xgemm.mali-t628.v6.0.cblas.txt](https://github.com/CNugteren/CLBlast/files/251837/clblast.dev.xgemm.mali-t628.v6.0.cblas.txt)

But I'm glad that this discussion will help you improve the verbose mode. I agree that testing against a single reference would suffice for now.

**Comment by CNugteren** [comment] 2016-05-07 10:25
OK, so then I'll close this issue.

In the meantime, two of the suggested changes will hopefully improve testing in the future:
* Indices are printed in verbose mode: https://github.com/CNugteren/CLBlast/commit/56aa1701c955546e049ec0dbe5b2777d592b5fc1
* Command-line arguments are added to test against either clBLAS or a CPU BLAS if both are installed: https://github.com/CNugteren/CLBlast/commit/6c9e08c5e288767d9afedb118c37694f63739cae

**Closed by CNugteren** 2016-05-07 10:25 UTC
