### ISSUE TITLE
"volatile int tid" in clblast_tuner_xgemm fails for Mesa 17,18 on certain graphics cards

### ISSUE THREAD

**Issue by infinity0** [CNugteren/CLBlast#298] opened 2018-07-17 15:38 UTC
Original issue is gcp/leela-zero#1612 and I can reproduce with current CLBlast master:

~~~~
$ grep PRETTY_NAME /etc/os-release 
PRETTY_NAME="Debian GNU/Linux buster/sid"
$ clinfo -l --raw
0: Clover
0:0: Radeon RX 580 Series (POLARIS10, DRM 3.23.0, 4.16.0-1-amd64, LLVM 6.0.1)
$ ./clblast_tuner_xgemm
* Options given/available:
    -platform 0 [=default]
    -device 0 [=default]
    -precision 32 (single) [=default]
    -m 1024 [=default]
    -n 1024 [=default]
    -k 1024 [=default]
    -alpha 2.00 [=default]
    -beta 2.00 [=default]
    -fraction 1.00 [=default]
    -runs 2 [=default]
    -max_l2_norm 0.00 [=default]

* Found 578 configuration(s)
* Parameters explored: GEMMK MWG NWG KWG MDIMC NDIMC MDIMA NDIMB KWI VWM VWN STRM STRN SA SB KREG 

|   ID | total |                                                                           param |       compiles |         time | GFLOPS |            status |
x------x-------x---------------------------------------------------------------------------------x----------------x--------------x--------x-------------------x
|  ref |     - |                                                                               - |             OK |     19.11 ms |      - |      reference OK |
x------x-------x---------------------------------------------------------------------------------x----------------x--------------x--------x-------------------x
|    1 |   578 |    0   16   16   32    8    8    8    8    2    1    1    0    0    0    0    1 |   OK    307 ms |      7.39 ms |  290.4 |     results match |
|    2 |   578 |    0   16   16   32    8    8    8    8    2    1    1    0    0    1    1    1 |  compilation error:   -11     |      - |                 - | <-- skipping
|    3 |   578 |    0   16   16   32    8    8    8    8    2    1    2    0    0    0    0    1 |   OK    296 ms |      8.86 ms |  242.4 |     results match |
|    4 |   578 |    0   16   16   32    8    8    8    8    2    1    2    0    0    1    1    1 |  compilation error:   -11     |      - |                 - | <-- skipping
|    5 |   578 |    0   16   16   32    8    8    8    8    2    2    1    0    0    0    0    1 |   OK    293 ms |      9.20 ms |  233.3 |     results match |
|    6 |   578 |    0   16   16   32    8    8    8    8    2    2    1    0    0    1    1    1 |  compilation error:   -11     |      - |                 - | <-- skipping
|    7 |   578 |    0   16   16   32    8    8    8    8    2    2    2    0    0    0    0    1 |   OK    283 ms |      8.06 ms |  266.4 |     results match |
|    8 |   578 |    0   16   16   32    8    8    8    8    2    2    2    0    0    1    1    1 |  compilation error:   -11     |      - |                 - | <-- skipping
|    9 |   578 |    0   16   16   32    8   16    8   16    2    1    1    0    0    0    0    1 |   OK    289 ms |     15.40 ms |  139.5 |     results match |
|   10 |   578 |    0   16   16   32    8   16    8   16    2    1    1    0    0    1    1    1 |  compilation error:   -11     |      - |                 - | <-- skipping
|   11 |   578 |    0   16   16   32    8   16    8   16    2    2    1    0    0    0    0    1 |   OK    292 ms |     11.68 ms |  183.9 |     results match |
|   12 |   578 |    0   16   16   32    8   16    8   16    2    2    1    0    0    1    1    1 |  compilation error:   -11     |      - |                 - | <-- skipping
^C
exit code 130
~~~~

The issue can be worked around by removing `volatile`. However the compilation error message is not directly about `volatile` but rather something like:

> :0:0: in function XgemmBatched void (i32, i32, i32, <2 x float> addrspace(1), <2 x float> addrspace(1), <2 x float> addrspace(1)*): unsupported initializer for address space

So I am not sure if it is Mesa's fault, or if CLBlast's code is buggy for certain graphics drivers (e.g. *sometimes* tid could get stored in an address space that doesn't support dynamic initialisers like `get_local_id()`).

The author of Leela Zero [reports that](https://github.com/gcp/leela-zero/issues/1612#issuecomment-405268953) the same code works for the same version of Mesa but on Arch/Manjaro and with a newer graphics card, POLARIS11. He originally thought it's Mesa's problem, but now the fact we both tried it with 18.1.3 suggests the problem may not be entirely Mesa.

For the time being I am patching away `volatile` on Debian but this affects all graphics cards, which is unnecessary. Do you have a better alternative idea for a work-around?

**Comment by CNugteren** [comment] 2018-07-20 19:55
Thanks for reporting and sorry for the slow response.

I myself actually don't have access to an AMD system with Mesa installed, so I can't reproduce it. However, I am considering getting rid of the `volatile` declaration all together... it was introduces long time ago to prevent certain compilers (NVIDIA if I recall correctly) from storing the thread-ID as a register and using uncessary register files, causing a low occupancy. That is a very device specific and low-level optimisation, which is against the philosophy of CLBlast.

I'll do some quick tests the coming days on some devices to see if it impacts performance negatively if we would remove the keyword.

**Comment by gcp** [comment] 2018-07-24 09:34
I did the same measurement as you (with slightly forked code), and also observed that on Mesa there is gain in having the volatile there.

So ironically the same driver series that is breaking is the one that would actually benefit.

I think that if we can identify what the actual software component is that is breaking on it, we can push upstream to get it fixed. Mesa is open source, after all.

**Comment by gcp** [comment] 2018-07-25 07:44
Filed as https://bugs.freedesktop.org/show_bug.cgi?id=107369

**Comment by CNugteren** [comment] 2018-09-16 18:07
@gcp Do you know if anyone is acting upon this bug? It has been silent in that thread since the end of July it seems.

**Comment by gcp** [comment] 2018-09-17 06:43
Doesn't seem like it's moving. Likely need to file a bug against Debian packaging for libclc and against LLVM for generating broken code.

**Comment by infinity0** [comment] 2018-09-17 07:01
I filed the Debian bug here already: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=904718 If the maintainer doesn't respond before the next release of leelaz I'll go ahead and fix it myself. (I'm a Debian developer with upload rights.)

Not sure what to do on the LLVM side, I'm less familiar with that project.

BTW I notice leelaz is including the contents of some CLBlast files in its source code. Would it be reasonable to load this at runtime from say `/usr/share/clblast/kernels` instead or are the interfaces too unstable to do that? If possible then this could be beneficial as we could update CLBlast in Debian independently of leelaz releases.

**Comment by gcp** [comment] 2018-09-17 16:16
>BTW I notice leelaz is including the contents of some CLBlast files in its source code. Would it be reasonable to load this at runtime from say /usr/share/clblast/kernels instead or are the interfaces too unstable to do that?

I think we use a more tightly integrated interface so it wouldn't work with the original CLBlast files (or it's not guaranteed to).

**Comment by infinity0** [comment] 2018-09-18 02:44
LLVM bug filed here, I forgot I already had an account so didn't have to wait for their manual registration process https://bugs.llvm.org/show_bug.cgi?id=38979

**Comment by gcp** [comment] 2018-10-23 09:28
Debian has updated packages now: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=904718

**Comment by CNugteren** [comment] 2018-11-20 18:55
Has anyone had a chance to test it again with CLBlast? Or do we still have to wait for the LLVM issue to be solved as well?

**Comment by CNugteren** [comment] 2019-01-23 19:16
@gcp, @infinity0, should I just close this issue, or is it worthwhile keeping this open until someone confirms that the LLVM and Debian bugfixes indeed fix everything? Has anyone tested?

**Comment by infinity0** [comment] 2019-01-23 23:50
I think you can close yes, stuff is fixed on the Debian side. The remaining issue in LLVM is not "user-visible", it would only be visible if someone does the same stupid thing we were in Debian (giving security hardening flags to the graphics-card target).

**Closed** 2019-01-24 19:08 UTC
Labels: correctness
