### ISSUE TITLE
This is not an issue but  I will use this place to share my finding ....

### ISSUE THREAD

**Issue by paolodalberto** [CNugteren/CLBlast#265] opened 2018-03-15 17:44 UTC
No closed issues should be left without showing the results of its solution :) 
I will use this ticket to share my results and configurations.

**Comment by paolodalberto** [comment] 2018-03-16 17:49
for me 0 is device 0 and it is a  Fiji
2 is device 2 and it is a Ellesmere

[gemm_2_16.pdf](https://github.com/CNugteren/CLBlast/files/1820254/gemm_2_16.pdf)
[gemm_0_16.pdf](https://github.com/CNugteren/CLBlast/files/1820255/gemm_0_16.pdf)
[gemm_2_64.pdf](https://github.com/CNugteren/CLBlast/files/1820256/gemm_2_64.pdf)
[gemm_0_64.pdf](https://github.com/CNugteren/CLBlast/files/1820257/gemm_0_64.pdf)
[gemm_2_3232.pdf](https://github.com/CNugteren/CLBlast/files/1820258/gemm_2_3232.pdf)
[gemm_0_3232.pdf](https://github.com/CNugteren/CLBlast/files/1820259/gemm_0_3232.pdf)
[gemm_2_6464.pdf](https://github.com/CNugteren/CLBlast/files/1820261/gemm_2_6464.pdf)
[gemm_0_6464.pdf](https://github.com/CNugteren/CLBlast/files/1820262/gemm_0_6464.pdf)

The tuned version is always better. The tuning give a name to the GPU that is used well when I use multiple GPUs

![clblasttunedscomplex](https://user-images.githubusercontent.com/15663156/37536268-4e72e364-2907-11e8-92a4-569ec8b14763.png)
![clblasttuneddouble](https://user-images.githubusercontent.com/15663156/37536269-4e9e92b6-2907-11e8-9ddd-71dc24acab47.png)
![clblasttuneddcomplex](https://user-images.githubusercontent.com/15663156/37536270-4ebb3cb8-2907-11e8-8a67-2affda3efea9.png)
![clblasttunedsingle](https://user-images.githubusercontent.com/15663156/37536271-4ed51b92-2907-11e8-8695-226df1f4e24c.png)
 
Without tuning, I had the performance for 4 GPUs worse than 2 GPUs for single precision. 

I am re-training for 6464 with a larger sample (fraction 10). Please advise for further tuning. 

This is great. I finally generated code optimized for the polaris architecture. 
http://www.fastmmw.com/2018/03/16/tuned-clblast-fast-matrix-multiply-by-ellesmere-and-fiji/

**Comment by paolodalberto** [comment] 2018-03-16 17:53
The database xgemm *.hpp

[xgemv.zip](https://github.com/CNugteren/CLBlast/files/1820286/xgemv.zip)

**Comment by paolodalberto** [comment] 2018-03-16 17:55
please let me know what I could do to improve the search for 6464 
I am a toddler and my understanding is limited by your careful advise.

**Comment by paolodalberto** [comment] 2018-03-17 22:56
Any suggestions ?

**Comment by CNugteren** [comment] 2018-03-18 08:35
Sorry, what is your question?

**Comment by paolodalberto** [comment] 2018-03-19 18:03
1) any suggestion how to drive the tuning for 6464 ?
2) could you see the knee in the performance plots (i.e., https://github.com/CNugteren/CLBlast/files/1820254/gemm_2_16.pdf) for problems >4K ? 

I tuned the gemms using clblast_tuner_xgemm  (not direct).

**Comment by CNugteren** [comment] 2018-03-19 19:19
1. No, I don't have any ideas for tuning except for running the included tuner with a larger amount of search options. It could be that despite the large search space the CLBlast kernel is suboptimal for a particular device / configuration. Performance difference can sometimes be caused by quite subtle changes, sometimes also caused by a sub-optimal OpenCL compiler.

2. Yes, I see the knee. This happens more often on AMD devices, e.g. in #134. It is due to 'partition camping', an issue still present in modern AMD GPUs. I also discussed this in #53 and 'solved' it using the staggered indices suggested by [an AMD article](http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/opencl-optimization-guide/#50401334_pgfId-472340). However, it might well be that for larger matrices this starts to become an issue again. Again, not much to due except for perhaps trying your luck with another tuning configuration?

**Comment by paolodalberto** [comment] 2018-03-19 21:17
1) I change the fraction to 10 (exploring 12,000 configurations). No much difference. I think clBLAS may use assembly and the compiler cannot cope with the difference in tools. 

2) let me check what partition camping is (unless is cache interference).

**Comment by CNugteren** [comment] 2018-03-30 07:34
1. No, clBLAS is also OpenCL-C code, not assembly. But the code is different and might be slightly better in some cases. I'm continuously trying to generalise the kernel further to improve it, so perhaps in the future it will be better.

2. Effects of partition camping might vary from device to device and from problem to problem. You can play with [this setting](https://github.com/CNugteren/CLBlast/blob/master/src/utilities/compile.cpp#L51) if you want to disable the AMD-specific optimisations for partition camping in CLBlast.

I'm going to close this since I don't see a real issue I have to take upon.

**Closed by CNugteren** 2018-03-30 07:34 UTC
Labels: performance, question
