### ISSUE TITLE
Compiling Darknet with CLBLAST

### ISSUE THREAD

**Issue by abhi1212** [CNugteren/CLBlast#290] opened 2018-06-16 01:45 UTC
I want to compile Darknet with CLBLAST.
When I add the clblast_cuda.h in my file I get an error
/usr/local/include/clblast_cuda.h(104): error: identifier "CUdeviceptr" is undefined
This points to the header file.
I have successfully compiled and executed  a standalone program with CLblast Cuda gemm, I have not faced any problems with that. I use nvcc -std=c++11 sgemm_cuda.cu -o sgemm -lcuda -lclblast for compiling.
I made sure to use similar flags while compiling with Darknet but the compilation fails.
OS- Ubuntu 14
Processor- Jetson Tx1 (ARM CPU cores)
Can some one please help @CNugteren

**Comment by CNugteren** [comment] 2018-06-16 10:13
I think you should also link to `nvrtc`, but that shouldn't cause this particular error. I'll take a closer look later, I'm on a mobile phone now.

**Comment by abhi1212** [comment] 2018-06-16 16:17
Hello Cedric,

Thanks, I tried multiple things but didn't work, the problem is that it is
basically  throwing Compilation errors inside the clblast header file
included, I have compiled only with Cuda.
By looking at the error messages, I think so it is not able to find the
cuda.h or nvrtc.h, but I am pretty sure that I have my paths set up
correctly.
The surprising part is that a standalone application works just fine.

Thanks
Abhishek

**Comment by CNugteren** [comment] 2018-06-17 12:48
Perhaps this is then an issue with the software you are compiling? The `clblast_cuda.h` has an include of `cuda.h` in it, which does device CUdeviceptr. Perhaps there is another `cuda.h` somewhere on your system or within the project you are compiling that is included instead?

**Comment by abhi1212** [comment] 2018-06-21 14:20
Hello @CNugteren , thanks a lot, apparently Darknet also had a file called cuda.h in its source directory.
Absolute paths helped me overcome the compilation issue.
The problem which I am facing now is that, my program run but my GEMM Kernel is never called.
My arrays are of floating data type, I have cast them to Cudeviceptr type.
**Cudeviceptr A= reinterpret_cast<Cudeviceptr>(&A_gpu);**
I think so this type conversion might be the problem. 
I don't get any kind of error it is just that my kernel is not called, I even used nvprof to check it.

I request for help @CNugteren

**Comment by abhi1212** [comment] 2018-06-24 17:22
Hello @CNugteren, I confirmed that casting is not an issue.
I am not sure why my kernel is not getting called.
Do we have to create a new context every time we have a call to CLblast GEMM?

I request for help @CNugteren

**Comment by CNugteren** [comment] 2018-06-24 23:18
I'm not sure what you mean. Could you create a small example (e.g. based on the sample GEMM code in CLBlast repo) that illustrates your issue?

**Comment by abhi1212** [comment] 2018-06-24 23:47
Yes, sure.
So, I have this gemm.c file from where I call the following function,

**gemm.c**
sgemm_gpu( TA,  TB, M, N, K, ALPHA, 
         A_gpu, lda, 
         B_gpu, ldb,
         BETA,
         C_gpu, ldc).

**Sgemm.cu**

So Inside the sgemm function, first I make sure all parameters are in accordance to the CLBLAST GEMM call

   const size_t m =(size_t) M;
    const size_t n =(size_t) N;
    const size_t k =(size_t) K;
    const float alpha = ALPHA;
    const float beta = BETA;
    const auto a_ld = K;
    const auto b_ld = N;
    const auto c_ld = N;
    const auto device_id = 0;
    CUdeviceptr A = reinterpret_cast<CUdeviceptr>(A_gpu) ;    //Coverting float pointer to CUdeviceptr
    CUdeviceptr B = reinterpret_cast<CUdeviceptr>(B_gpu); 
    CUdeviceptr C = reinterpret_cast<CUdeviceptr>(C_gpu);

    cuInit(0);
    CUdevice device;
    cuDeviceGet(&device, device_id);
    CUcontext context;
    cuCtxCreate(&context, 0, device);
    
    auto status = clblast::Gemm(clblast::Layout::kRowMajor,
                              clblast::Transpose::kNo, clblast::Transpose::kNo,
                              m, n, k,
                              alpha,
                              A_gpu, 0, a_ld,
                              B_gpu, 0, b_ld,
                              beta,
                              C_gpu, 0, c_ld,
                              context, device);

This is how I call the CLblast Gemm function, but the function never gets called.

**Comment by abhi1212** [comment] 2018-06-25 00:39
This is the profiling result
![image](https://user-images.githubusercontent.com/22337618/41825471-9744ac40-77ee-11e8-8b90-6ccdd69766e6.png)

The Gemm kernel never gets called

**Comment by CNugteren** [comment] 2018-06-25 01:08
What is the status code returned by CLBlast? If the kernel is not called, probably the status code is not OK and will indicate what the problem is.

**Comment by abhi1212** [comment] 2018-06-25 03:49
Hello @CNugteren ,

Thanks, I thought that I will get a runtime error is something went wrong, I did not check for the status earlier.
I did check the status now and it is **1022**
That means Matrix A is not valid.
OR 
Matrix A is not a valid Open CL Buffer.
I am using the Cuda version of the Library.
I am getting a float pointer to a buffer as Input which I am converting to CUdeviceptr by
 reinterpret_cast(A_gpu), I even tried A= (CUdeviceptr) A_gpu.

**Comment by abhi1212** [comment] 2018-06-26 04:46
Hello @CNugteren, Do you think my the problem is my conversion to float * to CUdeviceptr?
I am really confused as to what is the potential cause of failure, the status code it returns is **1022.**

**Comment by CNugteren** [comment] 2018-06-26 11:34
I'm not sure, but as far as I understand the CUdeviceptr and regular CUDA memory pointers are interchangable. [Here as some details](http://www.cudahandbook.com/2013/08/why-does-cuda-cudeviceptr-use-unsigned-int-instead-of-void/), suggesting something along the lines of `CUdeviceptr A; A = (CUdeviceptr) (uintptr_t) A_gpu;` for your example.

If I were you, I would start with the provide CUDA GEMM example, and then try to make it work using regular a CUDA runtime device pointer (e.g. `float * dev_ptr`).

**Comment by abhi1212** [comment] 2018-07-05 20:36
Hello @CNugteren , Thanks for your tips I was able to compile Darkenet with CLblast.
As, you know there are multiple calls to  GEMM in a CNN.
After my first call to Clblast gemm, I get the output in my C array, and subsequently a copy kernel is called to access it. I get a segmentation fault for it.
So I can have only 1 GEMM call.
My observation is that, I am using clblast::Gemm. I am not particularly using sgemm because I am not sure how to use it.
This might be causing an offer error in the output array.
Do you have any idea what might be going wrong?

**Comment by CNugteren** [comment] 2018-07-06 17:43
> I was able to compile Darkenet with CLblast

Good to hear, glad it works now :-)

> After my first call to Clblast gemm, I get the output in my C array, and subsequently a copy kernel is called to access it. I get a segmentation fault for it.

I can't help you debug your own code, there are examples and API documentation on how to use it. However, it could be related to a currently open bug, which is now fixed in the latest master. Could you check if that helps?

> My observation is that, I am using clblast::Gemm. I am not particularly using sgemm

The sample should help you with that. The precision is a template argument, so either calling `clblast::Gemm<float>(...)` or just passing a float value for alpha will do it for you :-)

**Comment by CNugteren** [comment] 2018-07-13 19:08
I don't think there are any open CLBlast issues here, so I'm closing this. If there is an issue with CLBlast, feel free to open a new issue.

**Closed by CNugteren** 2018-07-13 19:08 UTC
Labels: question
