### ISSUE TITLE
Xtrsm test: STRSM routine goes out of memory

### ISSUE THREAD

**Issue by mirh** [CNugteren/CLBlast#229] opened 2017-12-16 21:49 UTC
Manjaro OS 17.1
AMD E-350 (w/ radeon hd 6310 graphics)
Fglrx 15.9

---
While testing the first 'regular behavior' memory usage explodes.

**Comment by CNugteren** [comment] 2017-12-17 13:00
Thanks for reporting this. A few questions:

1. This is running on your AMD GPU, or on the CPU?
2. Could you share the full output of the TRSM test result (e.g. as a Github Gist if too large), preferably even using the `--verbose` option?
3. Are you testing with AMD's clBLAS as a reference or with a regular CPU BLAS? Perhaps try both just to make sure the issue is in CLBlast and not in the reference library.
4. Are you talking about CPU or GPU memory usage when you say 'explodes'?

**Comment by mirh** [comment] 2017-12-17 13:26
> This is running on your AMD GPU, or on the CPU?

GPU. When I force device 1 to run on CPU though, everything just works though. 
For the records, device name is just reported as `''` now. 

> Are you testing with AMD's clBLAS as a reference or with a regular CPU BLAS? 

Ehrm.. I have some difficulty trying to understand how parameters for this work. 

> Are you talking about CPU or GPU memory usage when you say 'explodes'?

CPU memory usage in a normal task manager. Not sure about gpu then. 

---
```
$ ./clblast_test_xtrsm -verbose

* Options given/available:
    -platform 0 [=default]
    -device 0 [=default]
    -full_test [false]
    -verbose [true]
    -cblas 1 [=default]

* Running on OpenCL device 'AMD Radeon HD 6310 Graphics'.
* Starting tests for the 'STRSM' routine. Legend:
   : -> Test produced correct results
   . -> Test returned the correct error code
   X -> Test produced incorrect results
   / -> Test returned an incorrect error code
   \ -> Test not executed: OpenCL-kernel compilation error
   o -> Test not executed: Unsupported precision
   - -> Test not completed: Reference CBLAS doesn't output error codes
* Testing with error margins of 0.5% (relative) and 0.001 (absolute)
* Testing 'regular behaviour' for '101 (row-major) 141 (left) 121 (upper) 111 (regular) 132 (unit)':
   Testing: m=7 n=7 lda=7 ldb=7 offa=0 offb=0 alpha=3.14 [CLBlast]^C
```

**Comment by CNugteren** [comment] 2017-12-17 15:01
OK, thanks for the info. Seems already the very first test crashes, and it crashes while running CLBlast, not while running the reference (also confirmed by the fact that it mentioned `-cblas 1` and that your CPU version works fine).

I'm suspecting now that it's actually the same issue as #207. I have it on the roadmap to work on this issue still this month, so hopefully that will be fixed soon. After, we should re-evaluate if your issue is also resolved. But it seems a similar set-up so quite likely.

**Comment by CNugteren** [comment] 2017-12-23 12:38
One thing you could already try for me perhaps: if you could replace in [this line](https://github.com/CNugteren/CLBlast/blob/master/src/kernels/level3/invert_diagonal_blocks.opencl#L59) `17` with `16`, i.e. setting `#define LOCALX 16`. Then, re-compile, and re-run the tests.

In the meantime I'm working on making these kernels tuneable, but it's not trivial, since I based them on other existing kernels and I'm not fully aware of what goes on exactly.

**Comment by mirh** [comment] 2017-12-23 14:10
Nope, same behavior. 

By the way, since you are targeting as wide and old as openCL as possible, could you define somewhere `CL_USE_DEPRECATED_OPENCL_2_0_APIS` so to avoid *lots* of warnings when clCreateCommandQueue  is compiled (at least with AMD APP SDK)?

**Comment by CNugteren** [comment] 2017-12-23 14:49
OK, too bad. Thanks for testing so quick though. I'll continue investigating that kernel. I don't have access to an AMD GPU this week though, so maybe it'll take 2 weeks or so.

About the OpenCL warnings, I just commited [this](https://github.com/CNugteren/CLBlast/commit/2b020d59f95b8c3fa7003e0da0d97f5d37e722a7). Is that what you need?

**Comment by mirh** [comment] 2017-12-23 15:15
Yes. 
Though 1_1 and 1_2 macros would seem useless TBH.

**Comment by CNugteren** [comment] 2017-12-24 11:30
> Though 1_1 and 1_2 macros would seem useless TBH
For you perhaps, but what if you are using OpenCL 1.1 or 1.2 headers? Anyway, they can't harm I guess, they were already there in the code.

I said before I didn't have access to an AMD test device this week, but I did still do a manual check of the code and also run he [cuda-memcheck tools](http://docs.nvidia.com/cuda/cuda-memcheck/#cuda-memcheck-tools). Those tools (memcheck, racecheck, initcheck, synccheck) all reported zero issues for TRSM, so that doesn't help us unfortunately.

One thing you could still do perhaps if you have time, is to recompile CLBlast in verbose mode. That means passing `-DVERBOSE=ON` to CMake (+ re-running CMake, + re-compiling) and then re-running the failing test. That should at least tell us in which kernel the issue is, because TRSM runs a couple of kernels actually.

**Comment by mirh** [comment] 2017-12-24 12:33
> For you perhaps, but what if you are using OpenCL 1.1 or 1.2 headers?

At least if we are talking of AMD APP SDK, that would mean using quite older versions - so I'm not really seeing the point. 
Moreover, none of the functions (that at least now are deprecated on previous 'feature levels') seem to be used by CLBlast. 

----
```
[DEBUG] Searching database for kernel 'Invert'
[DEBUG] Device type 'GPU'; vendor 'AMD'
[DEBUG] Device name 'AMD Radeon HD 6310 Graphics'; architecture 'Loveland'
[DEBUG] Found architectures of vendor 'default' and type 'default'
[DEBUG] Found devices of architecture type 'default'
[DEBUG] Found parameters for device type 'default'
[DEBUG] INVERT_Invert_16_0_4_4
[DEBUG] Compiling routine 'INVERT-32 (single)'
^C

**Comment by CNugteren** [comment] 2017-12-27 16:25
Thanks for testing in verbose mode. Actually, that shows something interesting: it is not a kernel which hangs, but it seems to be that the AMD compiler is unable to cope with the 'Invert' kernel. If that is really the case, then this is a bug on AMD's side, but let's try to work around it.

I've made a branch `trsm_compilation` with two things you can try:
* The invert kernel is a bit re-factored/simplified (at least for a human more readable). Small chance it fixes the issue, but who knows?
* I've added a new test `clblast_test_compile_invert` which only compiles the Invert kernel. This is made just to be 100% sure that that's indeed the issue. Could you run this test and see if you encounter the same issue? Thanks!

If the new test indeed also fails and you feel more adventurous you could start removing bits and piece s from the `src/kernels/level3/invert_diagonal_blocks_part1.opencl` file and try to isolate which lines of code make the compiler crash.

**Comment by mirh** [comment] 2017-12-27 19:02
I'm having some difficulty understanding what to tell cmake to have the test compile.

**Comment by CNugteren** [comment] 2017-12-27 19:04
After you've checked out the branch, you'll have to re-run CMake, e.g. `cmake -DTESTS=ON ..`. And then you can run the test by just executing the binary, e.g. `./clblast_test_compile_invert`.

**Comment by mirh** [comment] 2017-12-28 23:31
Oh right. I had forgot to remove alltests. 
clblast_test_compile_invert triggers the thing, yes. 

As for experimenting.. I played around with the initial constants and defines, to no avail. The remainder feels a bit too much intrepid.

**Comment by CNugteren** [comment] 2017-12-29 10:32
OK, thanks for testing. So this is actually an AMD APP issue then... hmmm.

What I meant was just to remove parts of the OpenCL kernel in that file. Or just remove entire functions there (or from `src/kernels/level3/invert_diagonal_blocks_part1.opencl` as well). That way we don't solve the issue (because the code will not work), but at least we will pinpoint which lines the AMD compiler doesn't like. Then we can re-write those in a different way I hope?

**Comment by blueberry** [comment] 2017-12-29 11:00
This might be related to #207

**Comment by CNugteren** [comment] 2017-12-30 20:17
Yes, I observed that already. It could very well be the same issue.

For those having this issue, including @mirh, could you do the following:
1. Check out the latest `trsm_compilation` branch, I've just pushed some changes there.
2. Compile and run the new `clblast_test_compile_invert` test, e.g. `make clblast_test_compile_invert && ./clblast_test_compile_invert`
3. Go to `src/kernels/level3/invert_diagonal_blocks_part1.opencl` at around line 61 and uncomment the line with `#define DISABLE_PART1`.
4. Run the test again (see step 2) and go back to step 3 but now uncomment the next line (e.g. `DISABLE_PART2`).
5. Repeat until the critical piece of code is found, perhaps even try to isolate it by finding the minimum subset of disable parts required to make the AMD OpenCL compiler work and the test pass.

**Comment by mirh** [comment] 2017-12-31 03:04
DISABLE_PART1 is the only one that seems having some effect (ie the test actually worked, finished, with nothing particularly special to report)

**Comment by CNugteren** [comment] 2017-12-31 13:10
OK, so if you just set `DISABLE_PART1` then everything works? So the issue lies within that piece of code it seems. I just changed some minor things in the 'part1' part of the invert kernel, perhaps those changes already fix the issue somehow. Could you try again with the latest version of this branch?

I also added two more defines in the latest commit to disable subparts of 'part1' (`DISABLE_PART1A` and `DISABLE_PART1B`). Could you try to find out which one of these parts makes it compile and which one doesn't (make sure not to disable the whole 'part1' at the same time, i.e. only 'part1a' or 'part1b')?

**Comment by mirh** [comment] 2017-12-31 14:17
Houston, we have a deal. 
I even got the INVERT-3232 test now. 

And I didn't need to touch anything.

**Comment by CNugteren** [comment] 2017-12-31 14:35
Good news :-) So to be clear: you didn't enable any of the defines, you just checked out the code without any changes? In that case the issue is solved: I'll remove the debug stuff and merge it in into master.

**Comment by mirh** [comment] 2017-12-31 14:47
Exactly. 
Was this total driver's fault then? If yes I guess it would be cool if you could keep a comment documenting the issue.

**Comment by CNugteren** [comment] 2017-12-31 15:15
I think it is a bug in AMD's OpenCL compiler. First of all, it should never hang, even if CLBlast's kernel's are not valid OpenCL code. It should exit with an error instead indicating invalid code. Second, all other compilers work fine with this kernel, so...

Anyway, I don't think AMD's APP is still maintained now that RoCm is out, so I'm not sure reporting a bug helps. And the issue is solved by this [small commit](https://github.com/CNugteren/CLBlast/commit/69226ae8282d25c33fec5a0e5c6998da286aeb77), the changes are quite minimal if you don't look at the `#ifndef` and `#endif` lines. Perhaps removing the `#pragma unroll` did the trick?

I have removed all debug code now, soon I will merge in #236. To be 100% sure, could you checkout the latest of `trsm_compilation` and try the `clblast_test_xtrsm` TRSM test?

**Comment by mirh** [comment] 2017-12-31 16:16
AMD APP is just the \*SDK\* name afaik. _Orca_, if any, is actually the compiler (or at least the driver stack). 
Then, surely my fglrx isn't being supported anymore.. But AMDGPU-PRO (which exhibited the same behavior in #235 and possibly #207) surely is. 
And ROCm doesn't intertwine with that. 

Said this anyway, my point wasn't really about documenting for AMD's sake, but more instead for other developers that might stumble on the bug somehow. 

`clblast_test_xtrsm` went perfect then (even though @blueberry @JayTay135 might want to give it a try too, given my potato doesn't support ZTRSM precision)

**Comment by JayTay135** [comment] 2017-12-31 19:17
Building from the latest commit of the trsm_compilation branch made everything work fine now. All tests of clblast_test_xtrsm passed and I was able to successfully run clblast_tuner_invert for all precisions and now have completed the tuning of my card. 

Thanks and Happy New Year.

**Comment by CNugteren** [comment] 2018-01-01 15:11
@mirh: Yes, you are right, the compiler is in the driver stack. For future documentation, [this commit](https://github.com/CNugteren/CLBlast/commit/69226ae8282d25c33fec5a0e5c6998da286aeb77) solved the issue.

@mirh and @JayTay135 Thanks for testing everything both, glad this issue is now resolved. The branch is now merged into master, so I'll close this issue. Happy new year :tada:

**Closed by CNugteren** 2018-01-01 15:11 UTC
Labels: bug
