### ISSUE TITLE
Failing with CL_INVALID_EVENT_WAIT_LIST

### ISSUE THREAD

**Issue by gcp** [CNugteren/CLBlast#71] opened 2016-06-30 00:19 UTC
I'm getting a "kKernelLaunchError" status code when launching my kernels. Adding a printf in the CheckError function to see the real underlying error, I'm getting a -57, i.e. CL_INVALID_EVENT_WAIT_LIST.

    const size_t M = outputs;         == 96
    const size_t N = spatial_out;    == 361
    const size_t K = filter_dim;       == 550

    auto queue_plain = queue();
    auto status = clblast::Gemm(
        clblast::Layout::kRowMajor,
        clblast::Transpose::kNo, clblast::Transpose::kNo,
        M, N, K,
        1.0f,
        weights[0](), 0, filter_dim,
        bufferCol(), 0, spatial_out,
        0.0f,
        bufferOutput(), 0, spatial_out,
        &queue_plain);

Looks like an issue with pad/transpose handling?

**Comment by gcp** [comment] 2016-06-30 08:21
For what it's worth, Release 0.7.1 works correctly, so this is a regression.

**Comment by CNugteren** [comment] 2016-06-30 09:01
Thanks for reporting. I am unable to reproduce the issue on my system though. Couple of questions:

1. Does the included `samples/sgemm.cpp` work for you? And what if you modify it to use your M, N, K dimensions and alpha/beta settings? And what if you remove the optional `event` argument? Those were the steps I did to try to reproduce the issue on my system anyway.
2. Even better - if you have the time - can you compile and run the included GEMM tests? See the README for instructions on how to build the tests.
3. Does the error also occur if you supply an event yourself (it is an option argument to the GEMM call)?
4. What hardware are you running on? Perhaps the issue is vendor specific?

**Comment by gcp** [comment] 2016-06-30 21:11
1) No, I get "Completed SGEMM in 241.348 ms with status -2048". Removing the event argument does not change this. I tried something similar with my own code, which is why I think the event problem occurs when the pad/transpose kernels are added internally in clblast.
2) I can't get it to recognize my OpenBLAS installation. I'm compiling on MSVC2015 in 32-bit mode which (I'm guessing) isn't the most tried and tested environment. (Compiling TUNERS also fails due to symbols not found in the clblast lib).
3) Yes, I tried this, with no effect. Again, I think the event issue is in clblasts own handling of sgemm.
4) AMD R9 390 on Windows 10, Win32 mode, AMD Crimson 16.6.2 driver. OpenCL lib and header are the Khronos reference OpenCL-ICD-Loader not AMD APP SDK (although I tried the latter for the sample, and it fails in the same way) Forcing the device to an Intel HD 530 with the latest Intel graphics drivers produces the same outcome.

**Comment by gcp** [comment] 2016-07-01 08:31
Turns out the event list issue is caused by stack corrupting bug earlier in CLBlast. Pull request with fix added.

**Comment by gcp** [comment] 2016-07-02 19:23
Pull request rebased to development branch #76

**Comment by CNugteren** [comment] 2016-07-03 14:35
Thanks for debugging this and creating a patch! The pull request is merged in now, so I am closing this issue.

**Closed by CNugteren** 2016-07-03 14:35 UTC
