### ISSUE TITLE
Poor Performance on GTX760 Ti

### ISSUE THREAD

**Issue by wngreene** [CNugteren/CLBlast#214] opened 2017-11-08 23:50 UTC
I've tuned on my GTX760 Ti card, but am getting poor performance. Most operations are ~ 1 GFLOPS.  For example the samples/sgemm.cpp test takes 5 ms, which (if I'm doing my math right) is roughly 1.67 GFLOPS. The matrixMul test in the CUDA8 samples takes 0.091 ms or ~90 GFLOPS with the same matrix sizes. Not sure if I'm doing something wrong and would appreciate any help.

Attached are the tuning results:
[gtx760ti.tar.gz](https://github.com/CNugteren/CLBlast/files/1455790/gtx760ti.tar.gz)

Here is the bash script I'm using to build, install, and tune:
[clblast.txt](https://github.com/CNugteren/CLBlast/files/1455825/clblast.txt)

**Comment by wngreene** [comment] 2017-11-09 16:46
Ah, missed the section in the readme on performance tests/comparisons. I'll give that a try and see if that reveals anything.

**Comment by CNugteren** [comment] 2017-11-09 17:22
Yes indeed, you should try the 'clients' (`-DCLIENTS=ON`). The sample itself is not a good way to measure performance. Also note that the first run will include the compilation time of the kernel, which could explain your observations.

**Comment by wngreene** [comment] 2017-11-09 18:47
K I ran the performance tests and now everything looks good (performance in the 100s of GFLOPS). The kernel compilation time was the issue. For some reason I thought the kernel binaries were cached on Nvidia cards so running an executable with a single kernel call multiple times (as opposed to running the kernel multiple times in a single executable) would give a valid timing result, but that doesn't seem to be the case.

And sorry, I thought I sent the json files originally:
[clblast_gtx760ti.tar.gz](https://github.com/CNugteren/CLBlast/files/1458787/clblast_gtx760ti.tar.gz)

I think you can close this issue - although I have another tuning/performance question regarding extremely rectangular matrices. I need to form the normal equations for a least squares problem - i.e. A^T *  A and A^T * b - where A is ~300000 x 6. Both of those products are pretty slow with CLBlast right now (20-30 ms per call). Would I be better trying to tune gemm/gemv or just call sdot multiple times? Thanks!

**Comment by CNugteren** [comment] 2017-11-09 20:23
Good to hear the issue is resolved now. I've added your tuning results to CLBlast, thanks!

About the rectangular matrices... you could try to run the GEMM and GEMV tuners with those specific m/n/k values and see if that helps. But rectangular matrices hasn't been a topic I studied with CLBlast yet, so it might be that you'll need to change the code to get optimal performance... Perhaps after I get some other more urgent things finished first I'll look at this at a later stage?

**Comment by wngreene** [comment] 2017-11-09 21:54
Sounds good. Thanks for the help and thanks for putting together this package - everything is extremely well documented and polished.

**Comment by CNugteren** [comment] 2017-11-14 17:41
No problem :-) I'll close this issue now, but will follow up on the rectangular matrices later when there is more time.

**Closed by CNugteren** 2017-11-14 17:41 UTC
Labels: performance
