### ISSUE TITLE
python gemm api fails

### ISSUE THREAD

**Issue by kodonnell** [CNugteren/CLBlast#260] opened 2018-03-10 08:07 UTC
Running the `sgemm.py` example, but changing:
```
-print("# Matrix C result: %s" % clc.get())
+c = clc.get()
+print("# Matrix C result: %s" % c)
```

throws an error. However the change:

```
-print("# Matrix C result: %s" % clc.get())
+d = clc.get()
+print("# Matrix C result: %s" % d)
```

gives no error. So, somehow, setting the result of `clc.get` to the same object that was used in `clc.set` is causing problems? Might be a question for `pyopencl` - a bit beyond me at this stage.

**Comment by CNugteren** [comment] 2018-03-11 10:45
I couldn't reproduce this on my system, it seems to work fine. I'll try on a few other devices as well.

**Comment by CNugteren** [comment] 2018-03-13 21:27
Also on another system it runs fine with your change. But what happens if you add `queue.finish()` just after the GEMM call was made but before retrieving the results?

**Comment by kodonnell** [comment] 2018-03-14 08:29
> I couldn't reproduce this on my system, it seems to work fine. I'll try on a few other devices as well.

It only happens off-an-on ... I repeated `python sgemm.py` it in a bash loop, and it was happening about half the time.

> But what happens if you add queue.finish() just after the GEMM call was made but before retrieving the results?

Still has failures, unfortunately. I think this may be related to me using Intel OpenCL - and maybe #243. I've tried to make the suggested changes (just adding them to `CMakeLists.txt`) but the errors are still happening

**Comment by CNugteren** [comment] 2018-03-24 19:00
Since the regular CLBlast tests fail as well for you (see #261), I'm closing this issue. If the other issue is solved, then let's revisit this, but most likely this is then also fixed.

**Closed by CNugteren** 2018-03-24 19:00 UTC
Labels: bug
