### ISSUE TITLE
Float16 GEMM on Adreno 330

### ISSUE THREAD

**Issue by sivagnanamn** [CNugteren/CLBlast#181] opened 2017-08-08 05:41 UTC
Followed the  `samples/haxpy.c` example to create float16 matrices and tried `CLBlastSgemm` on Adreno 330. Getting `Error number -1011 CL_INVALID_D3D9_RESOURCE_NV or CL_INVALID_DX9_RESOURCE_INTEL`.

**Comment by CNugteren** [comment] 2017-08-08 18:28
Could you provide a bit more info? Do other half-precision kernels work on your device? Do the CLBlast tests pass? Where is the error generated - in the CLBlast routine?

Also, how did you get those error codes? Are they printed? In CLBlast an error -1011 just indicates that you are running out of GPU memory:
```
(from clblast.h)
kInsufficientMemoryA       = -1011, // Matrix A's OpenCL buffer is too small
```

**Comment by sivagnanamn** [comment] 2017-08-09 01:45
Compiled the library with `-DSAMPLES=ON`, when executing `clblast_sample_haxpy_c` it works fine in Adreno 330 with OpenCL 1.1 (output shown below).

```
Input values at index 0: alpha * a[0] + b[0] == 0.500 * 2.199 + 0.400
Completed HAXPY with status 0
Output value at index 0: b[0] = 1.499
```
I have written few custom kernels for normalization, scaling etc they work fine for half-precision. This error code (-1011) gets generated when invoking `CLBlastSgemm` operation. For 32 bit precision the same code works fine. 

If I remove `CLBlastSgemm` and add my custom GEMM implementation, it works fine without any errors.

According to `README.md` half-precision support in CLBlast should work on latest Pascal architecture NVIDIA GPU's. But executing `clblast_sample_haxpy_c` on latest NVIDIA 1080 Ti (Pascal architecture, with OpenCL 1.2) throws error(output shown below):

```
Input values at index 0: alpha * a[0] + b[0] == 0.500 * 2.199 + 0.400
CLBlast: Run-time error: -2045
Completed HAXPY with status -2045
```
In Adreno, doing `make` after `cmake -DSAMPLES=ON ..` throws error and stops abrupty. Error log attached.

[Make_error.txt](https://github.com/CNugteren/CLBlast/files/1210018/Make_error.txt)

**Comment by sivagnanamn** [comment] 2017-08-09 06:29
I checked the supported extensions in NVIDIA 1080 Ti, looks like it doesnt support `cl_khr_fp16`

```
=== 1 OpenCL platform(s) found: ===
  PROFILE = FULL_PROFILE
  VERSION = OpenCL 1.2 CUDA 8.0.0
  NAME = NVIDIA CUDA
  VENDOR = NVIDIA Corporation
  EXTENSIONS = cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer
```

**Comment by CNugteren** [comment] 2017-08-09 15:39
Sorry I don't see any relation to your earlier reported issue in your last message. I do see two other issues you address:

1. The 1080 Ti indeed doesn't have FP16 support, only the P100 Pascal GPU has.
2. The compilation error you mention is related to `cl.hpp` which is [automatically downloaded by CMake](https://github.com/CNugteren/CLBlast/blob/master/CMakeLists.txt#L254). Double check if it is correctly done and otherwise [download it yourself](https://www.khronos.org/registry/OpenCL/api/2.1/cl.hpp).

**Comment by sivagnanamn** [comment] 2017-08-09 15:49
Sorry if the message was not to the point.

In order to test float16 support in Adreno 330, I used haxpy sample provided under `samples/` folder. haxpy worked fine with float16 inputs. 

I'm getting Error -1011 while invoking  `CLBlastSgemm` function with float16 inputs. `CLBlastSgemm` works fine with default float32 inputs.

**Comment by CNugteren** [comment] 2017-08-09 19:26
OK, so then I understand error -1011 is from the `CLBlastHgemm` call (assuming you made a typo in your post). In that case this is perfectly normal: in CLBlast an error -1011 just indicates that you are having an incorrectly sized buffer:
```
(from clblast.h)
kInsufficientMemoryA       = -1011, // Matrix A's OpenCL buffer is too small
```
So double check your buffer sizes!

**Comment by CNugteren** [comment] 2017-08-21 17:36
Too bad HGEMM seems a lot slower than SGEMM. Let's try to figure out what's happening:

1. Could you run the same experiments with the included CLBlast 'clients'? They measure performance as well and also compute the performance in GFLOPS. That way we are sure that the benchmarks are done correctly (e.g. ignoring the compilation of the kernels and such). You can see the README how to compile them (set `-DCLIENTS=ON` to CMake).

2. Compare the numbers against the hardware specs. Right now we don't know if SGEMM is fast, perhaps it is slow as well compared to what the GPU can do? So compute the GFLOPS numbers and compare it to the theoretical GFLOPS of single-precision and half-precision on your device.

**Comment by sivagnanamn** [comment] 2017-08-22 02:33
1. I've attached the SGEMM vs HGEMM benchmark on the above mentioned MNK sizes.

2. As per the hardware spec given [here](http://kyokojap.myweb.hinet.net/gpu_gflops/) , Adreno 330 is capable to provide 158.4 GFLOPS.

[SGEMM_Vs_HGEMM_Adreno330_Benchmark.txt](https://github.com/CNugteren/CLBlast/files/1240603/SGEMM_Vs_HGEMM_Adreno330_Benchmark.txt)

**Comment by CNugteren** [comment] 2017-08-22 18:25
OK, thanks for the info! Yes so indeed HGEMM performance is horrible, but also SGEMM performance is not super good. Some of your matrices are not too rectangular and they should perform decent. You can of course test with the clients to see what the performance of 1024x1024x1024 is, but I don't expect much more.

One thing I noted is that there are no tuning results for half-precision GEMM: you provided earlier on only results for single-precision. Perhaps that could bring the performance up a bit, but even then it's not too good. So I think there is something else more fundamentally wrong. Perhaps Qualcomm's OpenCL has the same issue as ARM's (see #128). Or perhaps there is something else wrong with the design of the CLBlast kernels and they just don't match the Adreno GPU architecture.

I just noted that I have an Android phone myself with an Adreno GPU. So if I have some spare time I'll see if I can get OpenCL and CLBlast running and perhaps then I can do some testing myself.

**Comment by TaihuLight** [comment] 2017-09-07 08:51
@sivagnanamn @CNugteren 
This means that the functions of  the clblast_half.h header, such as half FloatToHalf(const float value) and float HalfToFloat(const half value) on the NVIDIA 1080Ti GPU? And the samples/haxpy.c example only run on the devices that support  cl_khr_fp16? It is correct?
I build the  samples/haxpy.c example on NVIDIA 1080Ti GPU + CUDA 8.0, and get the error as follow:
And I want to know how to solve, or I can not build and run haxpy.c on  1080Ti GPU?

**Comment by TaihuLight** [comment] 2017-09-07 08:54
@sivagnanamn @CNugteren 
This means that the functions of  the clblast_half.h header, such as half FloatToHalf(const float value) and float HalfToFloat(const half value) on the NVIDIA 1080Ti GPU? And the samples/haxpy.c example only run on the devices that support  cl_khr_fp16? It is correct?
I build the  samples/haxpy.c example on NVIDIA 1080Ti GPU + CUDA 8.0, and get the error as follow:
And I want to know how to solve, or I can not build and run haxpy.c on  1080Ti GPU?
========
g++ -L/usr/local/cuda-8.0/lib64 -L/home/jiulonghu/Downloads/CLBlast-1.0.1-Linux-x64/lib -L/usr/lib/x86_64-linux-gnu -o "clblastdemo"  ./src/haxpy.o   -lOpenCL -lcltune -lclblast -lblas
./src/haxpy.o: In function `main':
/home/jiulonghu/workspace/clblastdemo/Debug/../src/haxpy.c:40: undefined reference to `FloatToHalf'
/home/jiulonghu/workspace/clblastdemo/Debug/../src/haxpy.c:64: undefined reference to `FloatToHalf'
/home/jiulonghu/workspace/clblastdemo/Debug/../src/haxpy.c:65: undefined reference to `FloatToHalf'
/home/jiulonghu/workspace/clblastdemo/Debug/../src/haxpy.c:67: undefined reference to `HalfToFloat'
/home/jiulonghu/workspace/clblastdemo/Debug/../src/haxpy.c:67: undefined reference to `HalfToFloat'
/home/jiulonghu/workspace/clblastdemo/Debug/../src/haxpy.c:67: undefined reference to `HalfToFloat'
/home/jiulonghu/workspace/clblastdemo/Debug/../src/haxpy.c:95: undefined reference to `HalfToFloat'
collect2: error: ld returned 1 exit status
make: *** [clblastdemo] Error 1
makefile:45: recipe for target 'clblastdemo' failed

**Comment by TaihuLight** [comment] 2017-09-07 08:54
@sivagnanamn @CNugteren
This means that the functions of the clblast_half.h header, such as half FloatToHalf(const float value) and float HalfToFloat(const half value) on the NVIDIA 1080Ti GPU? And the samples/haxpy.c example only run on the devices that support cl_khr_fp16? It is correct?
I build the samples/haxpy.c example on NVIDIA 1080Ti GPU + CUDA 8.0, and get the error as follow:
And I want to know how to solve, or I can not build and run haxpy.c on 1080Ti GPU?

g++ -L/usr/local/cuda-8.0/lib64 -L/home/jiulonghu/Downloads/CLBlast-1.0.1-Linux-x64/lib -L/usr/lib/x86_64-linux-gnu -o "clblastdemo" ./src/haxpy.o -lOpenCL -lcltune -lclblast -lblas
./src/haxpy.o: In function main': /home/jiulonghu/workspace/clblastdemo/Debug/../src/haxpy.c:40: undefined reference toFloatToHalf'
/home/jiulonghu/workspace/clblastdemo/Debug/../src/haxpy.c:64: undefined reference to FloatToHalf' /home/jiulonghu/workspace/clblastdemo/Debug/../src/haxpy.c:65: undefined reference toFloatToHalf'
/home/jiulonghu/workspace/clblastdemo/Debug/../src/haxpy.c:67: undefined reference to HalfToFloat' /home/jiulonghu/workspace/clblastdemo/Debug/../src/haxpy.c:67: undefined reference toHalfToFloat'
/home/jiulonghu/workspace/clblastdemo/Debug/../src/haxpy.c:67: undefined reference to HalfToFloat' /home/jiulonghu/workspace/clblastdemo/Debug/../src/haxpy.c:95: undefined reference toHalfToFloat'
collect2: error: ld returned 1 exit status
make: *** [clblastdemo] Error 1
makefile:45: recipe for target 'clblastdemo' failed

**Comment by sivagnanamn** [comment] 2017-09-07 10:08
@TaihuLight  You can compile `haxpy `example in 1080Ti, but during execution you'll get error. 1080Ti doesn't support float16 datatype. You can compile using -DSAMPLES=ON option and you'll find the `haxpy `sample executable in your build directory.

**Comment by TaihuLight** [comment] 2017-09-07 13:35
Yes, I can do it as you. But I also want to know how to build haxpy.c seperatly. After install the clblast successfully, I build it by using the following command .

 but it

**Comment by CNugteren** [comment] 2017-09-07 17:01
I think @sivagnanamn is perfectly right (thanks for helping out by the way):

1. Half-precision FP16 is not supported on GTX 1080 Ti and thus it will not run
2. It is easiest to compile using CMake and setting `-DSAMPLES=ON`. If you want to know how it is done (to be able to reproduce yourself), use `make VERBOSE=1` to see the actual compiler and linker commands. The missing functions are defined as inline functions in `clblast_half.h` by the way.

**Comment by sivagnanamn** [comment] 2017-09-25 03:15
@CNugteren Any improvement in GEMM performance on Qualcomm Adreno GPU's? I don't think unrolling alone will improve the performance in Qualcomm. 

Please share if you have any other suggestions.

**Comment by CNugteren** [comment] 2017-09-25 06:46
I have not tested that yet unfortunately. I'll see if I can make time for it soon.

**Comment by CNugteren** [comment] 2017-09-26 19:27
I started to install the NDK and compile the library, but I realised there is no OpenCL library for my device (Nexus 5X). I cannot find it on the device itself, and I cannot find it online either. So I'm afraid I cannot help right now.

I also tried to compile CLBlast using CMake and the NDK, but ran into quite some issues. I've started some documentation in #2949e15, but still couldn't get it fully working on my machine. How do you compile it?

**Comment by sivagnanamn** [comment] 2017-09-26 23:45
I'm not using Adreno on Smartphone. I'm experimenting with an Snapdragon dev kit board that runs on Linaro(flavour of Ubuntu). I followed the normal compilation steps for a Linux PC, it worked.

**Comment by sivagnanamn** [comment] 2017-09-27 07:11
Is it possible to tune GEMM individually for my different matrices and launch the respective kernels based on input dimension?

For ex:
Tune GEMM for -m 16 -n 200704 -k 27 ==> Save best kernel parameters as "A"
Tune GEMM for -m 32 -n 50176 -k 144 ==> Save best kernel parameters as "B"
...

And during execution when -m 16 -n 200704 -k 27 dimension matrices are passed as input, launch GEMM kernel with "A" set of parameters

**Comment by CNugteren** [comment] 2017-09-28 06:34
OK, maybe I should buy such a dev-kit as well if they are not too expensive. But that'll mean a bit longer term. Which board do you have/recommend?

There is an [interface](https://github.com/CNugteren/CLBlast/blob/master/include/clblast.h#L662) in CLBlast to set the tuning parameters manually. You could do that just before launching your kernel, possibly in an if-statement: e.g. if m == 16 then set_parameters(A) else set_parameters(B). But right now this would require re-compilation every time. I'm working on the `preparation_for_size_specific_parameters` branch to make it possible to save multiple compiled kernels in the cache, so that would speed-up things significantly.

Still, I think there might be an issue related to the kernel not be optimal in some sense to the hardware. I'll have to get access first in order to investigate further.

**Comment by sivagnanamn** [comment] 2017-09-28 06:44
Below 3 are my suggestions(I use FlightKit):

[FlightKit](https://www.intrinsyc.com/vertical-development-platforms/qualcomm-snapdragon-flight/)
[InForce 6540](https://www.inforcecomputing.com/products/single-board-computers-sbc/qualcomm-snapdragon-805-inforce-6540-sbc) 
[FireFly RK3399](https://www.kickstarter.com/projects/1771382379/firefly-rk3399-six-core-64-bit-high-performance-pl)

They're very useful for learning & building cool stuff.

**Comment by CNugteren** [comment] 2017-10-08 08:59
OK, those boards area bit expensive it seems. I bound a Dragonboard 410c devkit for $75, but apparently that doesn't have OpenCL support under Linux, only Android (@psyhtest: could you confirm?). In that case it makes more sense to get hold of a Qualcomm Android phone with OpenCL support. I'll see if I can loan one for a bit.

**Comment by psyhtest** [comment] 2017-10-09 23:04
@CNugteren Correct, DragonBoard 410c only supports [OpenCL under Android](https://discuss.96boards.org/t/opencl-on-android/1108).

**Comment by sivagnanamn** [comment] 2017-11-02 06:24
@TaihuLight  Were you able to solve your `undefined reference to FloatToHalf'` issue. Currently I'm facing the same while trying an standalone `FloatToHalf` example even after including `clblast_half.h` and linking clblast library.

**Comment by TaihuLight** [comment] 2018-03-29 07:49
@CNugteren Does NVIDIA Tesla P100 GPU (Pascal architecture) has FP16 support? How to enable it, due to I can not get the extension of cl_khr_fp16  using the following code:

**Comment by sivagnanamn** [comment] 2018-03-29 07:59
These are the extensions for NVIDIA P100 GPU

`cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer`

src: [https://devtalk.nvidia.com/default/topic/1008480/cuda-setup-and-installation/power8-p100-opencl-not-working/](https://devtalk.nvidia.com/default/topic/1008480/cuda-setup-and-installation/power8-p100-opencl-not-working/)

**Comment by TaihuLight** [comment] 2018-03-29 08:03
@sivagnanamn  Yes, I get the same extensions for NVIDIA P100 GPU, but CNugteren can get cl_khr_fp16 extension for P100 GPU, I do not how to do that!

**Comment by sivagnanamn** [comment] 2018-03-29 08:22
@TaihuLight I believe P100 doesn't support `cl_khr_fp_16` extension. So it will not support `half` (16 bit) operations. @CNugteren  please confirm.

To verify that, you can add the below line to any of your OpenCL kernels & compile it. You'll get an error saying this is not supported.

`#pragma OPENCL EXTENSION cl_khr_fp16 : enable`

**Comment by TaihuLight** [comment] 2018-03-29 09:39
@sivagnanamn  Could you have a successful code for running OpenCL code with cl_half  to share with me?

**Comment by CNugteren** [comment] 2018-03-29 17:20
@TaihuLight Is your question related to CLBlast at all? You are quoting non-CLBlast code and showing a non-CLBlast test program? So perhaps this is not the right place to ask.

But to answer your question, if your device/platform setup doesn't support `cl_khr_fp16`, then it doesn't support it. As far as I understand it, P100 only has `cl_khr_fp16` on x86 systems, not on PowerPC. The hardware of course does support FP16, but then you would have to use CUDA if NVIDIA doesn't support it through OpenCL.

**Comment by TaihuLight** [comment] 2018-03-30 00:38
Thank you for your reply. I want to use clblast with cl_half, but I first need to test the device P100 GPU, wether it supoort half routies on  the x86 system ubuntu 16.04 with CUDA 9.0 .  I test it , but get the above result.

**Comment by CNugteren** [comment] 2018-03-30 07:39
Then I'm afraid that's an issue you have to take to NVIDIA. If your OpenCL says your device doesn't support `cl_khr_fp16` then there is nothing I can do about it.

If you are willing to give up OpenCL, then there is an experimental [CUDA back-end to CLBlast](https://github.com/CNugteren/CLBlast/blob/master/doc/installation.md#compiling-clblast-with-a-cuda-back-end) which also supports FP16. However, then you might as well use cuBLAS I guess?

**Comment by GuntherSchuler** [comment] 2018-09-25 21:46
Hi! 
Not sure if this is the place to ask, but I'm trying to get FP16 GEMM working on the Adreno 530  GPU and can't seem to get a result. It has cl_khr_fp16 enabled, and the clblast::Gemm<T> call runs with no errors, but always produces a zeroed matrix. When run with single precision I get the expected matrix result. 

Running clblast_sample_haxpy_c produces the correct result. 

I've been testing on a modified samples/sgemm.cpp which calls Gemm<half> or Gemm<single>
on various matrix sizes. Is this a problem with how I am using the library, or is there a problem with the board itself?

**Comment by CNugteren** [comment] 2018-09-26 09:49
The first thing I would recommend to do is to try to run the GEMM tests in CLBlasts (see [here](https://github.com/CNugteren/CLBlast/blob/master/doc/testing.md#compiling-the-correctness-tests)) to make sure that you don't have some kind of issue in your code.

**Comment by GuntherSchuler** [comment] 2018-09-26 22:29
Thanks @CNugteren, 
The GEMM tests run fine, a couple have an invalid temp buffer size error, but I don't think that is related. When the exact same code is run with single precision I get the correct results. I've verified that the HalfToFloat and FloatToHalf functions appear to be functioning correctly. I've also tried simply copying a buffer of halfs to the device and back and the values are retained, so it seems like the Gemm kernel is running, but producing a matrix of zeros when called with half precision. Single precision works fine. 

I'm investigating farther, since as far as I can tell the half precision tuners ran fine.

**Comment by GuntherSchuler** [comment] 2018-10-22 17:53
apologies for the long long delay, something else came up and I haven't had a chance to look at this. I've done some sanity checks, and the problem I was having was a bug in my code causing alpha to be set wrong.

**Comment by CNugteren** [comment] 2018-10-22 19:43
@GuntherSchuler Glad to hear it works now

@sivagnanamn Perhaps time to revisit the original issue: is it still an issue? With the new kernels speed should be a better on the Adreno GPU. Is HGEMM still slower than SGEMM, or is there actually some benefit now?

**Comment by CNugteren** [comment] 2018-10-28 13:34
OK, I'll close this issue. Let's re-open (or open a new issue) whenever someone reports performance issues with HGEMM on Adreno specifically.

**Closed by CNugteren** 2018-10-28 13:34 UTC
Labels: performance
